namespace Exampler_ERP.Models
{
  public class StoreProcedure
  {
    string var = @"
USE [Exampler_ERP]
GO
/****** Object:  StoredProcedure [dbo].[GetFaceAttendanceForwarding]    Script Date: 10/30/2024 3:11:26 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
Create PROCEDURE [dbo].[GetFaceAttendanceForwarding]
    @MonthID INT,
    @YearID INT,
    @BranchID INT
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @LateComingAppID INT, 
            @EarlyGoingAppID INT, 
            @EarlyComingAppID INT, 
            @LateGoingAppID INT,
            @LateGraceMinute INT, 
            @EarlyGoingGraceMinute INT, 
            @EarlyComingGraceMinute INT, 
            @LateGoingGraceMinute INT,
            @LateComingPercent DECIMAL(5, 2), 
            @EarlyGoingPercent DECIMAL(5, 2), 
            @EarlyComingPercent DECIMAL(5, 2), 
            @LateGoingPercent DECIMAL(5, 2);

    -- Fetch values from HR_GlobalSettings
    SELECT TOP 1 
        @LateComingAppID = LateAppID,
        @EarlyGoingAppID = EarlyGoingAppID,
        @LateGraceMinute = LateGraceMinute,    
        @LateComingPercent = LateValueofHours,
        @EarlyGoingGraceMinute = EarlyGoingGraceMinute,
        @EarlyGoingPercent = EarlyGoingValueofHours,
        @EarlyComingAppID = EarlyComingAppID,
        @EarlyComingGraceMinute = EarlyComingGraceMinute,
        @EarlyComingPercent = EarlyComingValueofHours,
        @LateGoingAppID = LateSeatingAppID,
        @LateGoingGraceMinute = LateSeatingGraceMinute,
        @LateGoingPercent = LateSeatingValueofHours
    FROM HR_GlobalSettings;

    SELECT 
        fa.EmployeeID, 
        fa.MarkDate, 
        FORMAT(fa.InTime, 'HH:mm') AS InTime, 
        FORMAT(fa.OutTime, 'HH:mm') AS OutTime,
        DATEDIFF(MINUTE, fa.InTime, fa.OutTime) / 60 AS DHours,
        DATEDIFF(MINUTE, fa.InTime, fa.OutTime) % 60 AS DMinutes,  
        CONCAT(RIGHT('00' + CAST(hre.FromDutyTime AS VARCHAR(2)), 2), ':00') AS FromDutyTime,
        CONCAT(RIGHT('00' + CAST(hre.ToDutyTime AS VARCHAR(2)), 2), ':00') AS ToDutyTime,
        
        -- Late Coming Calculation with grace period
        CASE 
            WHEN CAST(fa.InTime AS TIME) > DATEADD(MINUTE, @LateGraceMinute, CAST(CONCAT(RIGHT('00' + CAST(hre.FromDutyTime AS VARCHAR(2)), 2), ':00') AS TIME))
            AND @LateComingAppID = 1 -- Only calculate if APPID is 1
            THEN CEILING(DATEDIFF(MINUTE, DATEADD(MINUTE, @LateGraceMinute, CAST(CONCAT(RIGHT('00' + CAST(hre.FromDutyTime AS VARCHAR(2)), 2), ':00') AS TIME)), CAST(fa.InTime AS TIME)) / 60.0)
            ELSE 0
        END AS LateComingGraceTime,

        -- Early Going Calculation with grace period
        CASE 
            WHEN CAST(fa.OutTime AS TIME) < DATEADD(MINUTE, -@EarlyGoingGraceMinute, CAST(CONCAT(RIGHT('00' + CAST(hre.ToDutyTime AS VARCHAR(2)), 2), ':00') AS TIME))
            AND @EarlyGoingAppID = 1 -- Only calculate if APPID is 1
            THEN CEILING(DATEDIFF(MINUTE, CAST(fa.OutTime AS TIME), DATEADD(MINUTE, -@EarlyGoingGraceMinute, CAST(CONCAT(RIGHT('00' + CAST(hre.ToDutyTime AS VARCHAR(2)), 2), ':00') AS TIME))) / 60.0)
            ELSE 0
        END AS EarlyGoingGraceTime,

        -- Per Day Salary Calculation
        FORMAT(CAST(hrsd.SalaryAmount AS FLOAT) / 
        (CASE 
            WHEN MONTH(fa.MarkDate) IN (4, 6, 9, 11) THEN 30.0  
            WHEN MONTH(fa.MarkDate) = 2 THEN 
                CASE 
                    WHEN YEAR(fa.MarkDate) % 4 = 0 AND (YEAR(fa.MarkDate) % 100 != 0 OR YEAR(fa.MarkDate) % 400 = 0) THEN 29.0 
                    ELSE 28.0 
                END
            ELSE 31.0 
        END), 'N2') AS PerDaySalary,

        -- Late Coming Deduction Calculation
        FORMAT(
            (CAST(hrsd.SalaryAmount AS FLOAT) / 
            (CASE 
                WHEN MONTH(fa.MarkDate) IN (4, 6, 9, 11) THEN 30.0
                WHEN MONTH(fa.MarkDate) = 2 THEN 
                    CASE 
                        WHEN YEAR(fa.MarkDate) % 4 = 0 AND (YEAR(fa.MarkDate) % 100 != 0 OR YEAR(fa.MarkDate) % 400 = 0) THEN 29.0
                        ELSE 28.0
                    END
                ELSE 31.0
            END) * 
            @LateComingPercent / 100) * 
            CASE 
                WHEN CAST(fa.InTime AS TIME) > DATEADD(MINUTE, @LateGraceMinute, CAST(CONCAT(RIGHT('00' + CAST(hre.FromDutyTime AS VARCHAR(2)), 2), ':00') AS TIME))
                AND @LateComingAppID = 1 -- Only calculate if APPID is 1
                THEN CEILING(DATEDIFF(MINUTE, DATEADD(MINUTE, @LateGraceMinute, CAST(CONCAT(RIGHT('00' + CAST(hre.FromDutyTime AS VARCHAR(2)), 2), ':00') AS TIME)), CAST(fa.InTime AS TIME)) / 60.0)
                ELSE 0
            END, 'N2') AS LateComingDeduction,

        -- Early Going Deduction Calculation
        FORMAT(
            (CAST(hrsd.SalaryAmount AS FLOAT) / 
            (CASE 
                WHEN MONTH(fa.MarkDate) IN (4, 6, 9, 11) THEN 30.0
                WHEN MONTH(fa.MarkDate) = 2 THEN 
                    CASE 
                        WHEN YEAR(fa.MarkDate) % 4 = 0 AND (YEAR(fa.MarkDate) % 100 != 0 OR YEAR(fa.MarkDate) % 400 = 0) THEN 29.0
                        ELSE 28.0
                    END
                ELSE 31.0
            END) * 
            @EarlyGoingPercent / 100) * 
            CASE 
                WHEN CAST(fa.OutTime AS TIME) < DATEADD(MINUTE, -@EarlyGoingGraceMinute, CAST(CONCAT(RIGHT('00' + CAST(hre.ToDutyTime AS VARCHAR(2)), 2), ':00') AS TIME))
                AND @EarlyGoingAppID = 1 -- Only calculate if APPID is 1
                THEN CEILING(DATEDIFF(MINUTE, CAST(fa.OutTime AS TIME), DATEADD(MINUTE, -@EarlyGoingGraceMinute, CAST(CONCAT(RIGHT('00' + CAST(hre.ToDutyTime AS VARCHAR(2)), 2), ':00') AS TIME))) / 60.0)
                ELSE 0
            END, 'N2') AS EarlyGoingDeduction,

        -- Early Coming Grace Time Calculation
        CASE 
            WHEN CAST(fa.InTime AS TIME) < DATEADD(MINUTE, -@EarlyComingGraceMinute, CAST(CONCAT(RIGHT('00' + CAST(hre.FromDutyTime AS VARCHAR(2)), 2), ':00') AS TIME))
            AND @EarlyComingAppID = 1 -- Only calculate if APPID is 1
            THEN CEILING(DATEDIFF(MINUTE, CAST(fa.InTime AS TIME), CAST(CONCAT(RIGHT('00' + CAST(hre.FromDutyTime AS VARCHAR(2)), 2), ':00') AS TIME)) / 60.0)
            ELSE 0
        END AS EarlyComingGraceTime,

        -- Late Going Grace Time Calculation
        CASE 
            WHEN CAST(fa.OutTime AS TIME) > CAST(CONCAT(RIGHT('00' + CAST(hre.ToDutyTime AS VARCHAR(2)), 2), ':00') AS TIME)
            AND @LateGoingAppID = 1 -- Only calculate if APPID is 1
            THEN CEILING(DATEDIFF(MINUTE, CAST(CONCAT(RIGHT('00' + CAST(hre.ToDutyTime AS VARCHAR(2)), 2), ':00') AS TIME), CAST(fa.OutTime AS TIME)) / 60.0)
            ELSE 0
        END AS LateGoingGraceTime,

        -- Early Coming Overtime Amount Calculation
    FORMAT(
        (CAST(hrsd.SalaryAmount AS FLOAT) / 
        (CASE 
            WHEN MONTH(fa.MarkDate) IN (4, 6, 9, 11) THEN 30.0  
            WHEN MONTH(fa.MarkDate) = 2 THEN 
                CASE 
                    WHEN YEAR(fa.MarkDate) % 4 = 0 AND (YEAR(fa.MarkDate) % 100 != 0 OR YEAR(fa.MarkDate) % 400 = 0) THEN 29.0 
                    ELSE 28.0 
                END
            ELSE 31.0 
        END) * 
        @EarlyComingPercent / 100) * 
        CASE 
            WHEN CAST(fa.InTime AS TIME) < DATEADD(MINUTE, -@EarlyComingGraceMinute, CAST(CONCAT(RIGHT('00' + CAST(hre.FromDutyTime AS VARCHAR(2)), 2), ':00') AS TIME))
            AND @EarlyComingAppID = 1 -- Only calculate if APPID is 1
            THEN CEILING(DATEDIFF(MINUTE, CAST(fa.InTime AS TIME), CAST(CONCAT(RIGHT('00' + CAST(hre.FromDutyTime AS VARCHAR(2)), 2), ':00') AS TIME)) / 60.0)
            ELSE 0
        END, 'N2') AS EarlyComingAmount,

    -- Late Going Amount Calculation
    FORMAT(
        (CAST(hrsd.SalaryAmount AS FLOAT) / 
        (CASE 
            WHEN MONTH(fa.MarkDate) IN (4, 6, 9, 11) THEN 30.0
            WHEN MONTH(fa.MarkDate) = 2 THEN 
                CASE 
                    WHEN YEAR(fa.MarkDate) % 4 = 0 AND (YEAR(fa.MarkDate) % 100 != 0 OR YEAR(fa.MarkDate) % 400 = 0) THEN 29.0
                    ELSE 28.0
                END
            ELSE 31.0
        END) * 
        @LateGoingPercent / 100) * 
        CASE 
            WHEN CAST(fa.OutTime AS TIME) > CAST(CONCAT(RIGHT('00' + CAST(hre.ToDutyTime AS VARCHAR(2)), 2), ':00') AS TIME)
            AND @LateGoingAppID = 1 -- Only calculate if APPID is 1
            THEN CEILING(DATEDIFF(MINUTE, CAST(CONCAT(RIGHT('00' + CAST(hre.ToDutyTime AS VARCHAR(2)), 2), ':00') AS TIME), CAST(fa.OutTime AS TIME)) / 60.0)
            ELSE 0
        END, 'N2') AS LateGoingAmount

    FROM
         CR_FaceAttendances fa
    JOIN 
        HR_Employees hre ON fa.EmployeeID = hre.EmployeeID
    JOIN 
        HR_Salarys hrs ON fa.EmployeeID = hrs.EmployeeID
    JOIN 
        HR_SalaryDetails hrsd ON hrs.SalaryID = hrsd.SalaryID and SalaryTypeID=1
    WHERE 
        MONTH(fa.MarkDate) = @MonthID 
        AND YEAR(fa.MarkDate) = @YearID
        AND hre.BranchTypeID = @BranchID
        --AND fa.MarkDate <= GETDATE(); 
END;
GO

Create PROCEDURE [dbo].[GetMonthlySalarySheet]
	@BranchID NVARCHAR(10),
    @EmployeeID NVARCHAR(10), -- Parameter to specify the EmployeeID
    @Month NVARCHAR(2),        -- Parameter for the month (e.g., '10' for October)
    @Year NVARCHAR(4)          -- Parameter for the year (e.g., '2024')
AS
BEGIN
    DECLARE @cols AS NVARCHAR(MAX),
            @query AS NVARCHAR(MAX),
            @EmployeeName NVARCHAR(MAX);

    -- Fetch EmployeeName by concatenating FirstName, FatherName, and FamilyName
    SELECT @EmployeeName = (FirstName + ' ' + FatherName + ' ' + FamilyName), @BranchID = BranchTypeID
    FROM HR_Employees
    WHERE EmployeeID = @EmployeeID and FinalApprovalID=1 and DeleteYNID != 1;

    -- Include Salary Types
    SELECT @cols = STUFF((
        SELECT DISTINCT ',' + QUOTENAME('Salary_' + SalaryTypeName) 
        FROM Settings_SalaryTypes where DeleteYNID != 1
        FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'), 1, 1, '');

    -- Step 1: Retrieve distinct column names with unique prefixes for all types
    SELECT @cols = @cols + ',' + STUFF((
        SELECT DISTINCT ',' + QUOTENAME('AdditionalAllowance_' + AdditionalAllowanceTypeName) 
        FROM Settings_AdditionalAllowanceTypes where DeleteYNID != 1
        FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'), 1, 1, '');

    -- Include OverTime Types
    SELECT @cols = @cols + ',' + STUFF((
        SELECT DISTINCT ',' + QUOTENAME('OverTime_' + OverTimeTypeName) 
        FROM Settings_OverTimeTypes where DeleteYNID != 1
        FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'), 1, 1, '');

    -- Include Deduction Types
    SELECT @cols = @cols + ',' + STUFF((
        SELECT DISTINCT ',' + QUOTENAME('Deduction_' + DeductionTypeName) 
        FROM Settings_DeductionTypes where DeleteYNID != 1
        FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'), 1, 1, '');

    -- Include Fixed Deduction Types
    SELECT @cols = @cols + ',' + STUFF((
        SELECT DISTINCT ',' + QUOTENAME('FixedDeduction_' + FixedDeductionTypeName) 
        FROM Settings_FixedDeductionTypes where DeleteYNID != 1
        FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'), 1, 1, '');

    -- Step 2: Create a dynamic SQL query to pivot the result ensuring all types appear in the same row
    SET @query = '
        SELECT ''' + @EmployeeID + ''' AS EmployeeID, ''' + @EmployeeName + ''' AS EmployeeName,
		(SELECT MonthTypeName From Settings_MonthTypes Where MonthTypeID=''' + @Month + ''') AS MonthName,''' + @BranchID + ''' AS BranchID,''' + @Month + ''' AS MonthID,''' + @Year + ''' AS Year,* FROM 
        ( 
            SELECT ''Salary_'' + SalaryTypeName AS TypeName, 
                ISNULL((SELECT hsd.SalaryAmount 
                         FROM HR_SalaryDetails hsd
                         INNER JOIN HR_Salarys hs ON hs.SalaryID = hsd.SalaryID
                         WHERE hsd.SalaryTypeID = sst.SalaryTypeID AND FinalApprovalID=1 
                           AND hs.EmployeeID = ''' + @EmployeeID + '''), 
                       0) AS Value
            FROM Settings_SalaryTypes sst 

            UNION ALL
            
            SELECT ''AdditionalAllowance_'' + AdditionalAllowanceTypeName AS TypeName, 
                ISNULL((SELECT haad.AdditionalAllowanceAmount 
                         FROM HR_AdditionalAllowanceDetails haad
                         INNER JOIN HR_AdditionalAllowances haa ON haa.AdditionalAllowanceID = haad.AdditionalAllowanceID
                         WHERE haad.AdditionalAllowanceTypeID = saat.AdditionalAllowanceTypeID AND FinalApprovalID=1
                           AND haa.EmployeeID = ''' + @EmployeeID + ''' 
                           AND MonthTypeID = ''' + @Month + ''' 
                           AND Year = ''' + @Year + '''), 
                   0) AS Value
            FROM Settings_AdditionalAllowanceTypes saat 

            UNION ALL
            
             SELECT ''Deduction_'' + DeductionTypeName AS TypeName,
                (SELECT SUM(hd.Amount) 
                        FROM HR_Deductions hd
                        WHERE hd.EmployeeID = ''' + @EmployeeID + ''' 
                          AND hd.Month = ''' + @Month + ''' 
                          AND hd.Year = ''' + @Year + ''' 
                          AND hd.DeductionTypeID = sd.DeductionTypeID AND FinalApprovalID=1 AND DeleteYNID != 1
                    )AS Value
            FROM Settings_DeductionTypes sd

            UNION ALL
            
            SELECT ''OverTime_'' + sott.OverTimeTypeName AS TypeName, 
                (SELECT SUM(hot.Amount) 
                 FROM HR_OverTimes hot
                 WHERE hot.OverTimeTypeID = sott.OverTimeTypeID AND FinalApprovalID=1 AND DeleteYNID != 1
                   AND hot.EmployeeID = ''' + @EmployeeID + ''' 
                   AND hot.MonthTypeID = ''' + @Month + ''' 
                   AND hot.Year = ''' + @Year + ''') AS Value
            FROM Settings_OverTimeTypes sott

            UNION ALL
            
            SELECT ''FixedDeduction_'' + sfdt.FixedDeductionTypeName AS TypeName, 
                ISNULL((SELECT hfdd.FixedDeductionAmount 
                         FROM HR_FixedDeductionDetails hfdd
                         INNER JOIN HR_FixedDeductions hfd ON hfd.FixedDeductionID = hfdd.FixedDeductionTypeID
                         WHERE hfdd.FixedDeductionTypeID = sfdt.FixedDeductionTypeID AND FinalApprovalID=1
                           AND hfd.EmployeeID = ''' + @EmployeeID + '''), 
                   0) AS Value
            FROM Settings_FixedDeductionTypes sfdt

        ) src    
        PIVOT
        (
            MAX(Value)
            FOR TypeName IN (' + @cols + ')
        ) AS pvt'; 

    -- Step 3: Execute the dynamic SQL
    EXEC sp_executesql @query;
EN

      ";

    string var2 = @"
INSERT INTO CR_LanguageRecords (LanguageRecordId, LabelName, LabelValue, Culture) VALUES 
('1', 'lbl_ EmployeeRequestDetails', 'ملازم کی درخواست کی تفصیلات', 'ur-PK'),
('2', 'lbl_ MonthlyPayRollDetails', 'ماہانہ پے رول کی تفصیلات', 'ur-PK'),
('3', 'lbl_ ProcessTypeForward', 'عمل کی قسم فارورڈ', 'ur-PK'),
('4', 'lbl_AbsenceManagement', 'غیر حاضری کا نظم', 'ur-PK'),
('5', 'lbl_Absent', 'غیر حاضر', 'ur-PK'),
('6', 'lbl_AccessRightByRole', 'کردار کے مطابق رسائی کا حق', 'ur-PK'),
('7', 'lbl_AccessRightByUser', 'صارف کے مطابق رسائی کا حق', 'ur-PK'),
('8', 'lbl_AccessRightsByRoleSetup', 'کردار کے لحاظ سے رسائی کے حقوق کی ترتیب', 'ur-PK'),
('9', 'lbl_AccessRightsByRoleSetupList', 'کردار کے لحاظ سے رسائی کی ترتیب کی فہرست', 'ur-PK'),
('10', 'lbl_AccessRightsByUserSetup', 'صارف کے لحاظ سے رسائی کے حقوق کی ترتیب', 'ur-PK'),
('11', 'lbl_AccessRightsByUserSetupList', 'صارف کے لحاظ سے رسائی کی ترتیب کی فہرست', 'ur-PK'),
('12', 'lbl_AccommodationExpenseRequest', 'رہائش کے اخراجات کی درخواست', 'ur-PK'),
('13', 'lbl_Account', 'اکاؤنٹ', 'ur-PK'),
('14', 'lbl_AccountTitle', 'اکاؤنٹ ٹائٹل', 'ur-PK'),
('15', 'lbl_AccountType', 'اکاؤنٹ کی قسم', 'ur-PK'),
('16', 'lbl_Action', 'عمل', 'ur-PK'),
('17', 'lbl_Active', 'فعال', 'ur-PK'),
('18', 'lbl_Add', 'نیا ', 'ur-PK'),
('19', 'lbl_AddApplicant', 'درخواست دہندہ شامل کریں', 'ur-PK'),
('20', 'lbl_AddContract', 'معاہدہ شامل کریں', 'ur-PK'),
('21', 'lbl_AddDocumentUpload', 'دستاویز اپ لوڈ شامل کریں', 'ur-PK'),
('22', 'lbl_AddEmployee', 'ملازم شامل کریں', 'ur-PK'),
('23', 'lbl_AddEmployeeRequest', 'ملازم درخواست شامل کریں', 'ur-PK'),
('24', 'lbl_AddHoliday', 'تعطیل شامل کریں', 'ur-PK'),
('25', 'lbl_AdditionalAllowance', 'اضافی الاؤنس', 'ur-PK'),
('26', 'lbl_AdditionalAllowanceDetails', 'اضافی الاؤنس کی تفصیلات', 'ur-PK'),
('27', 'lbl_AdditionalAllowanceList', 'اضافی الاؤنس', 'ur-PK'),
('28', 'lbl_AdditionalAllowanceType', ' اضافی الاؤنس کی قسم', 'ur-PK'),
('29', 'lbl_AdditionalAllowanceTypeID', ' اضافی الاؤنس کی قسم  نمبر', 'ur-PK'),
('30', 'lbl_AdditionalAllowanceTypeList', ' اضافی الاؤنس کی قسم  کی فہرست', 'ur-PK'),
('31', 'lbl_AdditionalAllowanceTypeName', ' اضافی الاؤنس کی قسم  کا نام', 'ur-PK'),
('32', 'lbl_AddJournalVoucher', 'نیا جرنل واؤچر شامل کریں', 'ur-PK'),
('33', 'lbl_AddMaterialRequisition', 'نئی مٹیریل کی درخواست شامل کریں', 'ur-PK'),
('34', 'lbl_AddNew', 'نیا شامل کریں', 'ur-PK'),
('35', 'lbl_AddNewAdditionalAllowanceType', 'نئی  اضافی الاؤنس کی قسم  شامل کریں', 'ur-PK'),
('36', 'lbl_AddNewBank', 'نیا بینک شامل کریں', 'ur-PK'),
('37', 'lbl_AddNewBranch', 'نئی برانچ شامل کریں', 'ur-PK'),
('38', 'lbl_AddNewCashAgainstSale', 'نئی فروخت کے عوض نقد شامل کریں', 'ur-PK'),
('39', 'lbl_AddNewCategoryType', 'نئی زمرہ کی قسم شامل کریں', 'ur-PK'),
('40', 'lbl_AddNewChequeBook', 'نئی چیک بُک شامل کریں', 'ur-PK'),
('41', 'lbl_AddNewDeduction', 'نئی کٹوتی شامل کریں', 'ur-PK'),
('42', 'lbl_AddNewDeductionSetup', 'نئی کٹوتی کی ترتیب  شامل کریں', 'ur-PK'),
('43', 'lbl_AddNewDeductionType', 'نئی کٹوتی کی قسم  شامل کریں', 'ur-PK'),
('44', 'lbl_AddNewDepartment', 'نئی شعبہ  شامل کریں', 'ur-PK'),
('45', 'lbl_AddNewDesignation', 'نئی عہدہ  شامل کریں', 'ur-PK'),
('46', 'lbl_AddNewEmployeeRequestType', 'نئی ملازم درخواست کی قسم  شامل کریں', 'ur-PK'),
('47', 'lbl_AddNewEmployeeRequestTypeForward', 'نیا ملازم درخواست قسم فارورڈ شامل کریں', 'ur-PK'),
('48', 'lbl_AddNewEmployeeStatusType', 'نئی ملازم حیثیت کی قسم  شامل کریں', 'ur-PK'),
('49', 'lbl_AddNewEndOfService', 'نیا اختتامِ سروس شامل کریں', 'ur-PK'),
('50', 'lbl_AddNewFaceAttendanceTimeAdjust', 'نئی چہرے کی حاضری وقت کی ترتیب شامل کریں', 'ur-PK'),
('51', 'lbl_AddNewFixedDeduction', 'نئی مقررہ کٹوتی شامل کریں', 'ur-PK'),
('52', 'lbl_AddNewFromStore', 'اسٹور سے نئی خریداری شامل کریں', 'ur-PK'),
('53', 'lbl_AddNewHeadofAccountFirst', 'نیا پہلا ہیڈ آف اکاؤنٹ شامل کریں', 'ur-PK'),
('54', 'lbl_AddNewHeadofAccountFive', 'نیا پانچواں ہیڈ آف اکاؤنٹ شامل کریں', 'ur-PK'),
('55', 'lbl_AddNewHeadofAccountFour', 'نیا چوتھا ہیڈ آف اکاؤنٹ شامل کریں', 'ur-PK'),
('56', 'lbl_AddNewHeadofAccountSecond', 'نیا دوسرا ہیڈ آف اکاؤنٹ شامل کریں', 'ur-PK'),
('57', 'lbl_AddNewHeadofAccountThird', 'نیا تیسرا ہیڈ آف اکاؤنٹ شامل کریں', 'ur-PK'),
('58', 'lbl_AddNewHolidayType', 'نئی تعطیل کی قسم  شامل کریں', 'ur-PK'),
('59', 'lbl_AddNewItem', 'نئی آئٹم شامل کریں', 'ur-PK'),
('60', 'lbl_AddNewItemCategoryType', 'نئی آئٹم کیٹیگری قسم شامل کریں', 'ur-PK'),
('61', 'lbl_AddNewItemComponentType', 'نئی آئٹم جزو قسم شامل کریں', 'ur-PK'),
('62', 'lbl_AddNewItemUnitType', 'نئی آئٹم یونٹ قسم کریں', 'ur-PK'),
('63', 'lbl_AddNewManufacturerType', 'نئی مینوفیکچرر قسم شامل کریں', 'ur-PK'),
('64', 'lbl_AddNewMaterialIssuance', 'نیا مواد جاری کریں', 'ur-PK'),
('65', 'lbl_AddNewMaterialReceived', 'نیا وصول شدہ مواد شامل کریں', 'ur-PK'),
('66', 'lbl_AddNewOverTimeRate', 'نیا اوور ٹائم شرح شامل کریں', 'ur-PK'),
('67', 'lbl_AddNewPaymentVoucher', 'نیا ادائیگی واؤچر شامل کریں', 'ur-PK'),
('68', 'lbl_AddNewProcessType', 'نئی عمل کی قسم  شامل کریں', 'ur-PK'),
('69', 'lbl_AddNewProcessTypeForward', 'نیا عمل کی قسم فارورڈ شامل کریں', 'ur-PK'),
('70', 'lbl_AddNewPurchaseRequest', 'نئی خریداری کی درخواست شامل کریں', 'ur-PK'),
('71', 'lbl_AddNewQualification', 'نئی اہلیت  شامل کریں', 'ur-PK'),
('72', 'lbl_AddNewReceivedVoucher', 'نیا وصولی واؤچر شامل کریں', 'ur-PK'),
('73', 'lbl_AddNewRoleType', 'نئی صارف کردار کی قسم  شامل کریں', 'ur-PK'),
('74', 'lbl_AddNewSalaryType', 'نئی تنخواہ کی قسم  شامل کریں', 'ur-PK'),
('75', 'lbl_AddNewSection', 'نئی قطعہ  شامل کریں', 'ur-PK'),
('76', 'lbl_AddNewSubQualification', 'نئی ضمنی اہلیت  شامل کریں', 'ur-PK'),
('77', 'lbl_AddNewTransferVoucher', 'نیا ٹرانسفر واؤچر شامل کریں', 'ur-PK'),
('78', 'lbl_AddNewUser', 'نئی صارف  شامل کریں', 'ur-PK'),
('79', 'lbl_AddNewVacationSettle', 'نئی چھٹی کی ادائیگی شامل کریں', 'ur-PK'),
('80', 'lbl_AddNewVacationType', 'نئی چھٹی کی قسم  شامل کریں', 'ur-PK'),
('81', 'lbl_AddNewVendor', 'نیا سپلائر شامل کریں', 'ur-PK'),
('82', 'lbl_AddNewVoucherType', 'نئی ووچر کی قسم شامل کریں', 'ur-PK'),
('83', 'lbl_AddNewWorkDay', 'نیا ورک ڈے شامل کریں', 'ur-PK'),
('84', 'lbl_AddOverTime', 'اوور ٹائم شامل کریں', 'ur-PK'),
('85', 'lbl_Address', 'پتہ', 'ur-PK'),
('86', 'lbl_AddThumbEnrollment', 'انگوٹھے کا اندراج شامل کریں', 'ur-PK'),
('87', 'lbl_AddVacation', 'چھٹی شامل کریں', 'ur-PK'),
('88', 'lbl_AddViaPO', 'خریداری آرڈر کے ذریعے شامل کریں', 'ur-PK'),
('89', 'lbl_All', 'تمام', 'ur-PK'),
('90', 'lbl_Allowance', 'الاونس', 'ur-PK'),
('91', 'lbl_AllowanceApproval', 'الاونس کی منظوری', 'ur-PK'),
('92', 'lbl_AllowedGracePeriod(Minutes)', 'مہلت کا مقررہ وقت (منٹوں میں)', 'ur-PK'),
('93', 'lbl_Amount', 'رقم', 'ur-PK'),
('94', 'lbl_AmountDuesForTheLeave', 'چھٹی کی واجب الادا رقم', 'ur-PK'),
('95', 'lbl_Applicant', 'درخواست دہندہ', 'ur-PK'),
('96', 'lbl_ApplicantBiodata', 'درخواست دہندہ بائیوڈیٹا', 'ur-PK'),
('97', 'lbl_ApplicantID', 'درخواست دہندہ نمبر', 'ur-PK'),
('98', 'lbl_ApplicantList', 'درخواست دہندگان کی فہرست', 'ur-PK'),
('99', 'lbl_ApplicantName', 'درخواست دہندہ کا نام', 'ur-PK'),
('100', 'lbl_Apply', 'درخواست', 'ur-PK'),
('101', 'lbl_ApplyDate', 'درخواست کی تاریخ', 'ur-PK'),
('102', 'lbl_ApplyDocumentUpload', 'دستاویز اپ لوڈ کی درخواست دیں', 'ur-PK'),
('103', 'lbl_ApplyVacation', 'چھٹی کے لیے درخواست دیں', 'ur-PK'),
('104', 'lbl_Approval', 'کردار', 'ur-PK'),
('105', 'lbl_ApprovalDetails', 'منظوری کی تفصیلات', 'ur-PK'),
('106', 'lbl_ApprovalForPurchaseOrder', 'خریداری کے آرڈر کی منظوری', 'ur-PK'),
('107', 'lbl_ApprovalProcessActions', 'منظوری کے عمل کی کارروائیاں', 'ur-PK'),
('108', 'lbl_ApprovalProcessDetails', 'منظوری عمل کی تفصیل', 'ur-PK'),
('109', 'lbl_ApprovalProcessID', 'منظوری عمل نمبر', 'ur-PK'),
('110', 'lbl_ApprovalProcessOverview', 'منظوری کے عمل کا جائزہ', 'ur-PK'),
('111', 'lbl_Approve', 'منظور کریں', 'ur-PK'),
('112', 'lbl_Approvedby', 'منظور کنندہ', 'ur-PK'),
('113', 'lbl_ApprovedDate', 'منظور شدہ تاریخ', 'ur-PK'),
('114', 'lbl_ApprovedMonthlySalarySheet', 'منظور شدہ ماہانہ تنخواہ شیٹ', 'ur-PK'),
('115', 'lbl_ApprovedMonthlySalarySheetList', 'منظور شدہ ماہانہ تنخواہ شیٹ کی فہرست', 'ur-PK'),
('116', 'lbl_ApprovedName', 'منظور شدہ نام', 'ur-PK'),
('117', 'lbl_AttachedDocuments', 'منسلک دستاویزات', 'ur-PK'),
('118', 'lbl_Attendance', 'حاضری', 'ur-PK'),
('119', 'lbl_AttendanceDuration', 'حاضری کا دورانیہ', 'ur-PK'),
('120', 'lbl_AutomaticDeductionforAbsences', 'غیر حاضری پر خودکار کٹوتی', 'ur-PK'),
('121', 'lbl_AutomaticDeductionforEarlyDepartures', 'جلدی جانے پر خودکار کٹوتی', 'ur-PK'),
('122', 'lbl_AutomaticDeductionforLateArrivals', 'تاخیر سے آنے پر خودکار کٹوتی', 'ur-PK'),
('123', 'lbl_AutomaticOvertimeforEarlyArrivals', 'جلدی آنے پر خودکار اوور ٹائم', 'ur-PK'),
('124', 'lbl_AutomaticOvertimeforLateStays', 'دیر تک رکنے پر خودکار اوور ٹائم', 'ur-PK'),
('125', 'lbl_AvailableStockQuantity', 'دستیاب اسٹاک کی مقدار', 'ur-PK'),
('126', 'lbl_BalanceOfTheAnnualLeave', 'سالانہ چھٹی کا باقی بیلنس', 'ur-PK'),
('127', 'lbl_BalanceQuantity', 'بقیہ مقدار', 'ur-PK'),
('128', 'lbl_Bank', 'بینک', 'ur-PK'),
('129', 'lbl_BankAccount', 'بینک اکاؤنٹ', 'ur-PK'),
('130', 'lbl_BankAccountList', 'بینک اکاؤنٹس کی فہرست', 'ur-PK'),
('131', 'lbl_BankAddress', 'بینک پتہ', 'ur-PK'),
('132', 'lbl_BankBranch', 'بینک برانچ', 'ur-PK'),
('133', 'lbl_BankContact', 'بینک رابطہ', 'ur-PK'),
('134', 'lbl_BankID', 'بینک  نمبر', 'ur-PK'),
('135', 'lbl_BankList', 'بینک کی فہرست', 'ur-PK'),
('136', 'lbl_BankName', 'بینک کا نام', 'ur-PK'),
('137', 'lbl_BarCode', 'بارکوڈ', 'ur-PK'),
('138', 'lbl_Billing', 'بلنگ', 'ur-PK'),
('139', 'lbl_BinLocation', 'بن لوکیشن', 'ur-PK'),
('140', 'lbl_BookshelvesRequest', 'کتابوں کی شیلفز کی درخواست', 'ur-PK'),
('141', 'lbl_Branch', 'برانچ', 'ur-PK'),
('142', 'lbl_BranchID', 'برانچ نمبر', 'ur-PK'),
('143', 'lbl_BranchList', 'برانچ کی فہرست', 'ur-PK'),
('144', 'lbl_BranchName', 'برانچ کا نام', 'ur-PK'),
('145', 'lbl_Browse', 'براؤز کریں', 'ur-PK'),
('146', 'lbl_ByMonth', 'مہینے کے لحاظ سے', 'ur-PK'),
('147', 'lbl_ByYear', 'سال کے لحاظ سے', 'ur-PK'),
('148', 'lbl_Cancel', 'منسوخ کریں', 'ur-PK'),
('149', 'lbl_Capture', 'کیپچر کریں', 'ur-PK'),
('150', 'lbl_CardPrint', 'کارڈ پرنٹ', 'ur-PK'),
('151', 'lbl_CardPrintList', 'کارڈ پرنٹ کی فہرست', 'ur-PK'),
('152', 'lbl_CashAgainstSale', 'فروخت کے عوض نقد', 'ur-PK'),
('153', 'lbl_CashAgainstSale', 'فروخت کے عوض نقد رقم', 'ur-PK'),
('154', 'lbl_CashAgainstSaleAccount', 'فروخت کے عوض نقد اکاؤنٹ', 'ur-PK'),
('155', 'lbl_CashAgainstSaleList', 'فروخت کے عوض نقد کی فہرست', 'ur-PK'),
('156', 'lbl_CashAgainstSaleName', 'فروخت کے عوض نقد کا نام', 'ur-PK'),
('157', 'lbl_Category', 'کیٹیگری', 'ur-PK'),
('158', 'lbl_CategoryType', 'شاخ کی نوعیت', 'ur-PK'),
('159', 'lbl_CategoryTypeID', 'زمرہ کی قسم نمبر', 'ur-PK'),
('160', 'lbl_CategoryTypeList', 'زمرہ کی اقسام کی فہرست', 'ur-PK'),
('161', 'lbl_CategoryTypeName', 'زمرہ کی قسم کا نام', 'ur-PK'),
('162', 'lbl_Cell', 'موبائل نمبر', 'ur-PK'),
('163', 'lbl_Change', 'تبدیلی', 'ur-PK'),
('164', 'lbl_ChangePassword', 'پاس ورڈ تبدیل کریں', 'ur-PK'),
('165', 'lbl_ChangePicture', 'تصویر تبدیل کریں', 'ur-PK'),
('166', 'lbl_Checkifthisitemhasalotnumberandexpirydate', 'چیک کریں کہ آیا اس آئٹم کے پاس لاٹ نمبر اور اختتامی تاریخ ہے', 'ur-PK'),
('167', 'lbl_Checkyourattendancerecordshere.', 'اپنی حاضری کا ریکارڈ یہاں چیک کریں۔', 'ur-PK'),
('168', 'lbl_ChequeBook', 'چیک بُک', 'ur-PK'),
('169', 'lbl_ChequeBookID', 'چیک بُک نمبر', 'ur-PK'),
('170', 'lbl_ChequeBookList', 'چیک بُک کی فہرست', 'ur-PK'),
('171', 'lbl_City', 'شہر', 'ur-PK'),
('172', 'lbl_Class', 'درجہ', 'ur-PK'),
('173', 'lbl_Close', 'بند', 'ur-PK'),
('174', 'lbl_ClosingBalance', 'اختتامی بیلنس', 'ur-PK'),
('175', 'lbl_ComfirmedVendor', 'تصدیق شدہ فروشندہ', 'ur-PK'),
('176', 'lbl_Comment', 'منظوری کے عمل کا جائزہ', 'ur-PK'),
('177', 'lbl_CompanyGrowth', 'کمپنی کی ترقی', 'ur-PK'),
('178', 'lbl_CompanyInformation', 'ادارے کی معلومات', 'ur-PK'),
('179', 'lbl_CompanyName', 'کمپنی کا نام', 'ur-PK'),
('180', 'lbl_ComparisonPassedVendor', 'منتخب شدہ فروخت کنندہ', 'ur-PK'),
('181', 'lbl_Components', 'اجزاء', 'ur-PK'),
('182', 'lbl_ConfigurationDetails', 'ترتیب کی تفصیلات', 'ur-PK'),
('183', 'lbl_ConfirmNewPassword', 'نیا پاس ورڈ کی تصدیق کریں', 'ur-PK'),
('184', 'lbl_Contact', 'رابطہ کریں', 'ur-PK'),
('185', 'lbl_Contract', 'معاہدہ', 'ur-PK'),
('186', 'lbl_ContractDetail', 'معاہدے کی تفصیل', 'ur-PK'),
('187', 'lbl_ContractEndDate', 'معاہدے کی اختتام کی تاریخ', 'ur-PK'),
('188', 'lbl_ContractEndDaysList', 'معاہدے کے اختتامی دنوں کی فہرست', 'ur-PK'),
('189', 'lbl_ContractExpiry', 'معاہدے کی میعاد ختم ہونا', 'ur-PK'),
('190', 'lbl_ContractID', 'معاہدہ  نمبر', 'ur-PK'),
('191', 'lbl_ContractList', 'معاہدوں کی فہرست', 'ur-PK'),
('192', 'lbl_ContractRenewal', 'معاہدہ کی تجدید', 'ur-PK'),
('193', 'lbl_ContractRenewalApproval', 'معاہدہ تجدید کی منظوری', 'ur-PK'),
('194', 'lbl_ContractRenewalDetails', 'معاہدے کی تجدید کی تفصیلات', 'ur-PK'),
('195', 'lbl_ContractRenewalList', 'معاہدہ تجدید کی فہرست', 'ur-PK'),
('196', 'lbl_ContractStartDate', 'معاہدے کی آغاز کی تاریخ', 'ur-PK'),
('197', 'lbl_ContractType', 'معاہدے کی قسم', 'ur-PK'),
('198', 'lbl_CostComparison', 'لاگت کا موازنہ', 'ur-PK'),
('199', 'lbl_CostComparisonList', 'لاگت کے موازنہ کی فہرست', 'ur-PK'),
('200', 'lbl_CostComparisonPrint', 'لاگت کے موازنہ کا پرنٹ', 'ur-PK'),
('201', 'lbl_CostComparisonsForm', 'لاگت کے موازنہ کا فارم', 'ur-PK'),
('202', 'lbl_Count', 'تعداد', 'ur-PK'),
('203', 'lbl_Country', 'ملک', 'ur-PK'),
('204', 'lbl_Credit', 'جمع', 'ur-PK'),
('205', 'lbl_CreditAmount', 'کریڈٹ رقم', 'ur-PK'),
('206', 'lbl_CreditCard', 'کریڈٹ کارڈ', 'ur-PK'),
('207', 'lbl_CricketKit', 'کرکٹ کٹ', 'ur-PK'),
('208', 'lbl_CurrentBalance', 'موجودہ بیلنس', 'ur-PK'),
('209', 'lbl_Dashboard', 'ڈیش بورڈ', 'ur-PK'),
('210', 'lbl_Data', 'معلومات', 'ur-PK'),
('211', 'lbl_Date', 'تاریخ', 'ur-PK'),
('212', 'lbl_DateOfCommencement', 'آغاز کی تاریخ', 'ur-PK'),
('213', 'lbl_DateOfCompletionOfWork', 'کام مکمل ہونے کی تاریخ', 'ur-PK'),
('214', 'lbl_Days', 'دن', 'ur-PK'),
('215', 'lbl_DCNo', 'ڈی سی نمبر', 'ur-PK'),
('216', 'lbl_Debit', 'منفی', 'ur-PK'),
('217', 'lbl_DebitAmount', 'ڈیبٹ رقم', 'ur-PK'),
('218', 'lbl_Decor', 'سجاوٹ', 'ur-PK'),
('219', 'lbl_DeducationDay', 'کٹوتی کا دن', 'ur-PK'),
('220', 'lbl_Deduction', 'کٹوتی', 'ur-PK'),
('221', 'lbl_DeductionApproval', 'کٹوتی کی منظوری', 'ur-PK'),
('222', 'lbl_DeductionDetail', 'کٹوتی کی تفصیل', 'ur-PK'),
('223', 'lbl_DeductionID', 'کٹوتی نمبر', 'ur-PK'),
('224', 'lbl_DeductionList', 'کٹوتیوں کی فہرست', 'ur-PK'),
('225', 'lbl_DeductionPercentageofDailyPay', 'یومیہ تنخواہ میں سے کٹوتی کا فیصد', 'ur-PK'),
('226', 'lbl_DeductionSetup', 'کٹوتی کی ترتیب', 'ur-PK'),
('227', 'lbl_DeductionSetupID', 'کٹوتی کی ترتیب  نمبر', 'ur-PK'),
('228', 'lbl_DeductionSetupList', 'کٹوتی کی ترتیب  کی فہرست', 'ur-PK'),
('229', 'lbl_DeductionSetupName', 'کٹوتی کی ترتیب  کا نام', 'ur-PK'),
('230', 'lbl_DeductionType', 'کٹوتی کی قسم', 'ur-PK'),
('231', 'lbl_DeductionTypeID', 'کٹوتی کی قسم  نمبر', 'ur-PK'),
('232', 'lbl_DeductionTypeList', 'کٹوتی کی قسم  کی فہرست', 'ur-PK'),
('233', 'lbl_DeductionTypeName', 'کٹوتی کی قسم  کا نام', 'ur-PK'),
('234', 'lbl_DeductionValue', 'کٹوتی کی قدر', 'ur-PK'),
('235', 'lbl_Delete', 'حذف کریں', 'ur-PK'),
('236', 'lbl_Department', 'شعبہ', 'ur-PK'),
('237', 'lbl_DepartmentID', 'شعبہ  نمبر', 'ur-PK'),
('238', 'lbl_DepartmentList', 'شعبہ  کی فہرست', 'ur-PK'),
('239', 'lbl_DepartmentName', 'شعبہ  کا نام', 'ur-PK'),
('240', 'lbl_Description', 'تفصیل', 'ur-PK'),
('241', 'lbl_DeservedAmount', 'واجب الادا رقم', 'ur-PK'),
('242', 'lbl_Designation', 'عہدہ', 'ur-PK'),
('243', 'lbl_DesignationID', 'عہدہ  نمبر', 'ur-PK'),
('244', 'lbl_DesignationList', 'عہدہ  کی فہرست', 'ur-PK'),
('245', 'lbl_DesignationName', 'عہدہ  کا نام', 'ur-PK'),
('246', 'lbl_DeskLampsRequest', 'ڈیسک لیمپس کی درخواست', 'ur-PK'),
('247', 'lbl_DesktopComputersRequest', 'ڈیسک ٹاپ کمپیوٹرز کی درخواست', 'ur-PK'),
('248', 'lbl_Details', 'تفصیلات', 'ur-PK'),
('249', 'lbl_Dining', 'ڈائننگ', 'ur-PK'),
('250', 'lbl_DirectManager', 'براہ راست مینیجر', 'ur-PK'),
('251', 'lbl_DirectManagerforEmployee', 'ملازم کے لیے براہ راست مینیجر', 'ur-PK'),
('252', 'lbl_DOB', 'تاریخ پیدائش', 'ur-PK'),
('253', 'lbl_Document', 'دستاویز اپ لوڈ', 'ur-PK'),
('254', 'lbl_Documentation', 'دستاویزی کارروائی', 'ur-PK'),
('255', 'lbl_DocumentName', 'دستاویز کا نام', 'ur-PK'),
('256', 'lbl_DocumentType', 'دستاویز کی قسم', 'ur-PK'),
('257', 'lbl_DocumentUploadList', 'دستاویز اپ لوڈ کی فہرست', 'ur-PK'),
('258', 'lbl_Download', 'ڈاؤن لوڈ', 'ur-PK'),
('259', 'lbl_DutyHours', 'ڈیوٹی کے اوقات', 'ur-PK'),
('260', 'lbl_DutyMinutess', 'ڈیوٹی کے منٹ', 'ur-PK'),
('261', 'lbl_Earbuds', 'ایئربڈز', 'ur-PK'),
('262', 'lbl_EarlyArrivalOvertimeManagement', 'جلدی آمد پر اوور ٹائم کا نظم', 'ur-PK'),
('263', 'lbl_EarlyComingAmount(Hours)', 'جلد آنے کی رقم (گھنٹے)', 'ur-PK'),
('264', 'lbl_EarlyComingHours', 'جلد آنے کے اوقات', 'ur-PK'),
('265', 'lbl_EarlyDepartureManagement', 'جلدی روانگی کا نظم', 'ur-PK'),
('266', 'lbl_EarlyGoingDeduction(Hours)', 'جلد جانے کی کٹوتی (گھنٹے)', 'ur-PK'),
('267', 'lbl_EarlyGoingHours', 'جلد جانے کے اوقات', 'ur-PK'),
('268', 'lbl_Edit', 'ترمیم کریں', 'ur-PK'),
('269', 'lbl_Edit DocumentUpload', 'دستاویز اپ لوڈ میں ترمیم کریں', 'ur-PK'),
('270', 'lbl_EditAccessRightsByRoleSetup', 'کردار کے لحاظ سے رسائی کی ترتیب میں ترمیم کریں', 'ur-PK'),
('271', 'lbl_EditAccessRightsByUserSetup', 'صارف کے لحاظ سے رسائی کی ترتیب میں ترمیم کریں', 'ur-PK'),
('272', 'lbl_EditAdditionalAllowanceType', ' اضافی الاؤنس کی قسم  میں ترمیم کریں', 'ur-PK'),
('273', 'lbl_EditApplicant', 'درخواست دہندہ میں ترمیم کریں', 'ur-PK'),
('274', 'lbl_EditBank', 'بینک میں ترمیم کریں', 'ur-PK'),
('275', 'lbl_EditBioData', 'بائیوڈیٹا میں ترمیم کریں', 'ur-PK'),
('276', 'lbl_EditBranch', 'برانچ میں ترمیم کریں', 'ur-PK'),
('277', 'lbl_EditCashAgainstSale', 'فروخت کے عوض نقد میں ترمیم کریں', 'ur-PK'),
('278', 'lbl_EditCategoryType', 'زمرہ کی قسم میں ترمیم کریں', 'ur-PK'),
('279', 'lbl_EditChequeBook', 'چیک بُک میں ترمیم کریں', 'ur-PK'),
('280', 'lbl_EditContract', 'معاہدے میں ترمیم کریں', 'ur-PK'),
('281', 'lbl_EditContractRenewal', 'معاہدہ تجدید میں ترمیم کریں', 'ur-PK'),
('282', 'lbl_EditDeductionSetup', 'کٹوتی کی ترتیب  میں ترمیم کریں', 'ur-PK'),
('283', 'lbl_EditDeductionType', 'کٹوتی کی قسم  میں ترمیم کریں', 'ur-PK'),
('284', 'lbl_EditDepartment', 'شعبہ  میں ترمیم کریں', 'ur-PK'),
('285', 'lbl_EditDesignation', 'عہدہ  میں ترمیم کریں', 'ur-PK'),
('286', 'lbl_EditedPurchaseRequest', 'ترمیم شدہ خریداری کی درخواست', 'ur-PK'),
('287', 'lbl_EditedPurchaseRequestApproval', 'ترمیم شدہ خریداری کی درخواست کی منظوری', 'ur-PK'),
('288', 'lbl_EditEmployee', 'ملازم میں ترمیم کریں', 'ur-PK'),
('289', 'lbl_EditEmployeeRequest', 'ملازم درخواست میں ترمیم کریں', 'ur-PK'),
('290', 'lbl_EditEmployeeRequestType', 'ملازم درخواست کی قسم  میں ترمیم کریں', 'ur-PK'),
('291', 'lbl_EditEmployeeRequestTypeApprovalSetup', 'ملازم درخواست قسم منظوری سیٹ اپ میں ترمیم کریں', 'ur-PK'),
('292', 'lbl_EditEmployeeRequestTypeForward', 'ملازم درخواست قسم فارورڈ میں ترمیم کریں', 'ur-PK'),
('293', 'lbl_EditEmployeeStatusType', 'ملازم حیثیت کی قسم  میں ترمیم کریں', 'ur-PK'),
('294', 'lbl_EditEndOfService', 'اختتامِ سروس میں ترمیم کریں', 'ur-PK'),
('295', 'lbl_EditFaceAttendanceTimeAdjust', 'چہرے کی حاضری وقت کی ترتیب میں ترمیم کریں', 'ur-PK'),
('296', 'lbl_EditFixedDeduction', 'مقررہ کٹوتی میں ترمیم کریں', 'ur-PK'),
('297', 'lbl_EditHeadofAccountFirst', 'پہلے ہیڈ آف اکاؤنٹ میں ترمیم کریں', 'ur-PK'),
('298', 'lbl_EditHeadofAccountFive', 'پانچویں ہیڈ آف اکاؤنٹ میں ترمیم کریں', 'ur-PK'),
('299', 'lbl_EditHeadofAccountFour', 'چوتھے ہیڈ آف اکاؤنٹ میں ترمیم کریں', 'ur-PK'),
('300', 'lbl_EditHeadofAccountSecond', 'دوسرے ہیڈ آف اکاؤنٹ میں ترمیم کریں', 'ur-PK'),
('301', 'lbl_EditHeadofAccountThird', 'تیسرے ہیڈ آف اکاؤنٹ میں ترمیم کریں', 'ur-PK'),
('302', 'lbl_EditHoliday', 'تعطیل میں ترمیم کریں', 'ur-PK'),
('303', 'lbl_EditHolidayType', 'تعطیل کی قسم  میں ترمیم کریں', 'ur-PK'),
('304', 'lbl_EditItem', 'آئٹم میں ترمیم کریں', 'ur-PK'),
('305', 'lbl_EditItemCategoryType', 'آئٹم کیٹیگری قسم میں ترمیم کریں', 'ur-PK'),
('306', 'lbl_EditItemComponentType', 'آئٹم جزو قسم میں ترمیم کریں', 'ur-PK'),
('307', 'lbl_EditItemUnitType', 'آئٹم یونٹ قسم میں ترمیم کریں', 'ur-PK'),
('308', 'lbl_EditJoining', 'شمولیت میں ترمیم کریں', 'ur-PK'),
('309', 'lbl_EditJournalVoucher', 'جرنل واؤچر میں ترمیم کریں', 'ur-PK'),
('310', 'lbl_EditManufacturerType', 'مینوفیکچرر قسم میں ترمیم کریں', 'ur-PK'),
('311', 'lbl_EditMaterialIssuance', 'مواد کے اجرا میں ترمیم کریں', 'ur-PK'),
('312', 'lbl_EditMaterialReceived', 'وصول شدہ مواد میں ترمیم کریں', 'ur-PK'),
('313', 'lbl_EditMaterialRequisition', 'مٹیریل کی درخواست میں ترمیم کریں', 'ur-PK'),
('314', 'lbl_EditOverTime', 'اوور ٹائم میں ترمیم کریں', 'ur-PK'),
('315', 'lbl_EditOverTimeRate', 'اوور ٹائم شرح میں ترمیم کریں', 'ur-PK'),
('316', 'lbl_EditPaymentVoucher', 'ادائیگی واؤچر میں ترمیم کریں', 'ur-PK'),
('317', 'lbl_EditProcessType', 'عمل کی قسم  میں ترمیم کریں', 'ur-PK'),
('318', 'lbl_EditProcessTypeApprovalSetup', 'عمل کی قسم منظوری سیٹ اپ میں ترمیم کریں', 'ur-PK'),
('319', 'lbl_EditProcessTypeForward', 'عمل کی قسم فارورڈ میں ترمیم کریں', 'ur-PK'),
('320', 'lbl_EditPurchaseRequest', 'خریداری کی درخواست میں ترمیم کریں', 'ur-PK'),
('321', 'lbl_EditQualification', 'اہلیت  میں ترمیم کریں', 'ur-PK'),
('322', 'lbl_EditReceivedVoucher', 'وصولی واؤچر میں ترمیم کریں', 'ur-PK'),
('323', 'lbl_EditRoleType', 'صارف کردار کی قسم  میں ترمیم کریں', 'ur-PK'),
('324', 'lbl_EditSalary', 'تنخواہ میں ترمیم کریں', 'ur-PK'),
('325', 'lbl_EditSalaryType', 'تنخواہ کی قسم  میں ترمیم کریں', 'ur-PK'),
('326', 'lbl_EditSection', 'قطعہ  میں ترمیم کریں', 'ur-PK'),
('327', 'lbl_EditSubQualification', 'ضمنی اہلیت  میں ترمیم کریں', 'ur-PK'),
('328', 'lbl_EditThumbEnrollment', 'انگوٹھے کے اندراج میں ترمیم کریں', 'ur-PK'),
('329', 'lbl_EditTransferVoucher', 'ٹرانسفر واؤچر میں ترمیم کریں', 'ur-PK'),
('330', 'lbl_EditUser', 'صارف  میں ترمیم کریں', 'ur-PK'),
('331', 'lbl_EditVacation', 'چھٹی میں ترمیم کریں', 'ur-PK'),
('332', 'lbl_EditVacationSettle', 'چھٹی کی ادائیگی میں ترمیم کریں', 'ur-PK'),
('333', 'lbl_EditVacationType', 'چھٹی کی قسم  میں ترمیم کریں', 'ur-PK'),
('334', 'lbl_EditVendor', 'سپلائر میں ترمیم کریں', 'ur-PK'),
('335', 'lbl_EditVoucherType', 'ووچر کی قسم میں ترمیم کریں', 'ur-PK'),
('336', 'lbl_EditWorkDay', 'ورک ڈے میں ترمیم کریں', 'ur-PK'),
('337', 'lbl_Education', 'تعلیم', 'ur-PK'),
('338', 'lbl_EducationDocument', 'تعلیمی دستاویز', 'ur-PK'),
('339', 'lbl_EducationDocumentList', 'تعلیمی دستاویزات کی فہرست', 'ur-PK'),
('340', 'lbl_Electronic', 'الیکٹرانک', 'ur-PK'),
('341', 'lbl_Email', 'ای میل', 'ur-PK'),
('342', 'lbl_Employee', 'ملازم', 'ur-PK'),
('343', 'lbl_EmployeeBioData', 'ملازم بائیو ڈیٹا', 'ur-PK'),
('344', 'lbl_EmployeeBioDataList', 'ملازم بائیو ڈیٹا کی فہرست', 'ur-PK'),
('345', 'lbl_EmployeeCode', 'ملازم کوڈ', 'ur-PK'),
('346', 'lbl_EmployeeDetails', 'ملازم کی تفصیلات', 'ur-PK'),
('347', 'lbl_EmployeeEducation', 'ملازم کی تعلیم', 'ur-PK'),
('348', 'lbl_EmployeeExperience', 'ملازم کا تجربہ', 'ur-PK'),
('349', 'lbl_EmployeeID', 'ملازم  نمبر', 'ur-PK'),
('350', 'lbl_EmployeeList', 'ملازمین کی فہرست', 'ur-PK'),
('351', 'lbl_EmployeeLogin', 'ملازم لاگ اِن', 'ur-PK'),
('352', 'lbl_EmployeeLogin-Pages', 'ملازم لاگ اِن - صفحات', 'ur-PK'),
('353', 'lbl_Employeement', 'ملازمت', 'ur-PK'),
('354', 'lbl_EmployeementBiodata', 'ملازم بائیوڈیٹا', 'ur-PK'),
('355', 'lbl_EmployeeName', 'ملازم کا نام', 'ur-PK'),
('356', 'lbl_EmployeePortal', 'ملازمین کا پورٹل', 'ur-PK'),
('357', 'lbl_EmployeeRequest', 'ملازم کی درخواست', 'ur-PK'),
('358', 'lbl_EmployeeRequestApproval', 'ملازم کی درخواست کی منظوری', 'ur-PK'),
('359', 'lbl_EmployeeRequestApprovalActions', 'Employee Request Approval Actions', 'ur-PK'),
('360', 'lbl_EmployeeRequestApprovalDetail', 'ملازم کی درخواست کی منظوری کی تفصیل', 'ur-PK'),
('361', 'lbl_EmployeeRequestApprovalID', 'ملازم کی درخواست منظوری نمبر', 'ur-PK'),
('362', 'lbl_EmployeeRequestApprovalOverview', 'ملازم کی درخواست کی منظوری کا جائزہ', 'ur-PK'),
('363', 'lbl_EmployeeRequestApprovals', 'ملازم کی درخواستوں کی منظوری', 'ur-PK'),
('364', 'lbl_EmployeeRequestApprovalSetup', 'ملازم درخواست منظوری سیٹ اپ', 'ur-PK'),
('365', 'lbl_EmployeeRequestForword', 'ملازم درخواست فارورڈ کریں', 'ur-PK'),
('366', 'lbl_EmployeeRequestID', 'ملازم درخواست  نمبر', 'ur-PK'),
('367', 'lbl_EmployeeRequestList', 'ملازم درخواستوں کی فہرست', 'ur-PK'),
('368', 'lbl_EmployeeRequestName', 'ملازم درخواست کی قسم کا نام', 'ur-PK'),
('369', 'lbl_EmployeeRequestType', 'ملازم درخواست کی قسم', 'ur-PK'),
('370', 'lbl_EmployeeRequestType', 'ملازم درخواست کی قسم', 'ur-PK'),
('371', 'lbl_EmployeeRequestTypeApprovalList', 'ملازم کی درخواست کی قسم کی منظوری کی فہرست', 'ur-PK'),
('372', 'lbl_EmployeeRequestTypeApprovalSetup', 'ملازم درخواست قسم منظوری سیٹ اپ', 'ur-PK'),
('373', 'lbl_EmployeeRequestTypeApprovalSetupID', 'ملازم درخواست منظوری سیٹ اپ نمبر', 'ur-PK'),
('374', 'lbl_EmployeeRequestTypeApprovalSetupList', 'ملازم درخواست قسم منظوری سیٹ اپ کی فہرست', 'ur-PK'),
('375', 'lbl_EmployeeRequestTypeForward', 'ملازم درخواست قسم فارورڈ', 'ur-PK'),
('376', 'lbl_EmployeeRequestTypeForwardList', 'ملازم درخواست قسم فارورڈ کی فہرست', 'ur-PK'),
('377', 'lbl_EmployeeRequestTypeID', 'ملازم درخواست کی قسم  نمبر', 'ur-PK'),
('378', 'lbl_EmployeeRequestTypeList', 'ملازم درخواست کی قسم  کی فہرست', 'ur-PK'),
('379', 'lbl_EmployeeRequestTypeName', 'ملازم درخواست کی قسم  کا نام', 'ur-PK'),
('380', 'lbl_EmployeeStatusType', 'ملازم حیثیت کی قسم', 'ur-PK'),
('381', 'lbl_EmployeeStatusTypeID', 'ملازم حیثیت کی قسم  نمبر', 'ur-PK'),
('382', 'lbl_EmployeeStatusTypeList', 'ملازم حیثیت کی قسم  کی فہرست', 'ur-PK'),
('383', 'lbl_EmployeeStatusTypeName', 'ملازم حیثیت کی قسم  کا نام', 'ur-PK'),
('384', 'lbl_End', 'اختتام', 'ur-PK'),
('385', 'lbl_EndDate', 'ختم ہونے کی تاریخ', 'ur-PK'),
('386', 'lbl_EndMonth', 'اختتام کا مہینہ', 'ur-PK'),
('387', 'lbl_EndOfService', 'اختتامِ سروس', 'ur-PK'),
('388', 'lbl_EndofService', 'سروس کا اختتام', 'ur-PK'),
('389', 'lbl_EndofServiceApproval', 'سروس اختتام کی منظوری', 'ur-PK'),
('390', 'lbl_EndofServiceBenefit', 'اختتامِ سروس فائدہ', 'ur-PK'),
('391', 'lbl_EndOfServiceDetails', 'اختتامِ سروس کی تفصیل', 'ur-PK'),
('392', 'lbl_EndOfServiceID', 'اختتامِ سروس نمبر', 'ur-PK'),
('393', 'lbl_EndOfServiceList', 'اختتامِ سروس کی فہرست', 'ur-PK'),
('394', 'lbl_EndYear', 'اختتام کا مہینہ', 'ur-PK'),
('395', 'lbl_EnrollmentDate', 'اندراج کی تاریخ', 'ur-PK'),
('396', 'lbl_Enter', 'درج', 'ur-PK'),
('397', 'lbl_EnterDescriptionHere', 'یہاں تفصیل درج کریں…', 'ur-PK'),
('398', 'lbl_EnterRessonHere', 'یہاں وجہ درج کریں…', 'ur-PK'),
('399', 'lbl_EthernetCablesRequest', 'ایتھرنیٹ کیبلز کی درخواست', 'ur-PK'),
('400', 'lbl_Evaluation', 'جائزہ', 'ur-PK'),
('401', 'lbl_EvaluationApproval', 'جائزہ کی منظوری', 'ur-PK'),
('402', 'lbl_EvaluationAssign', 'جائزہ تفویض کریں', 'ur-PK'),
('403', 'lbl_EvaluationList', 'جائزہ کی فہرست', 'ur-PK'),
('404', 'lbl_EvaluationQuestions', 'جائزہ سوالات', 'ur-PK'),
('405', 'lbl_EvaluationTemplate', 'جائزہ ٹیمپلیٹ', 'ur-PK'),
('406', 'lbl_Excel', 'ایکسل', 'ur-PK'),
('407', 'lbl_Expenses', 'اخراجات', 'ur-PK'),
('408', 'lbl_ExpensesThisWeek', 'اس ہفتے کے اخراجات', 'ur-PK'),
('409', 'lbl_Experience', 'تجربہ', 'ur-PK'),
('410', 'lbl_ExperienceCertificate', 'تجربے کا سرٹیفکیٹ', 'ur-PK'),
('411', 'lbl_ExperienceCertificateList', 'تجربے کے سرٹیفکیٹس کی فہرست', 'ur-PK'),
('412', 'lbl_ExperienceDocumentList', 'تجربے کی دستاویزات کی فہرست', 'ur-PK'),
('413', 'lbl_ExternalHardDrivesRequest', 'ایکسٹرنل ہارڈ ڈرائیوز کی درخواست', 'ur-PK'),
('414', 'lbl_ExternalMicrophoneRequest', 'ایکسٹرنل مائیکروفون کی درخواست', 'ur-PK'),
('415', 'lbl_ExternalSpeakersRequest', 'ایکسٹرنل اسپیکرز کی درخواست', 'ur-PK'),
('416', 'lbl_FaceAttendance', 'چہرے کی حاضری', 'ur-PK'),
('417', 'lbl_FaceAttendanceForwarding', 'چہرے کی حاضری فارورڈنگ', 'ur-PK'),
('418', 'lbl_FaceAttendanceForwardingList', 'چہرے کی حاضری فارورڈنگ کی فہرست', 'ur-PK'),
('419', 'lbl_FaceAttendanceID', 'چہرے کی حاضری نمبر', 'ur-PK'),
('420', 'lbl_FaceAttendanceList', 'چہرے کی حاضری کی فہرست', 'ur-PK'),
('421', 'lbl_FaceAttendanceReport', 'چہرے کی حاضری رپورٹ', 'ur-PK'),
('422', 'lbl_FaceAttendanceTimeAdjust', 'چہرے کی حاضری وقت کی ترتیب', 'ur-PK'),
('423', 'lbl_FaceAttendanceTimeAdjustDetails', 'چہرے کی حاضری وقت کی ترتیب کی تفصیل', 'ur-PK'),
('424', 'lbl_FaceAttendanceTimeAdjustList', 'چہرے کی حاضری وقت کی ترتیب کی فہرست', 'ur-PK'),
('425', 'lbl_FamilyName', 'خاندان کا نام', 'ur-PK'),
('426', 'lbl_Fashion', 'فیشن', 'ur-PK'),
('427', 'lbl_FatherName', 'والد کا نام', 'ur-PK'),
('428', 'lbl_Fax', 'فیکس', 'ur-PK'),
('429', 'lbl_Federal', 'وفاقی', 'ur-PK'),
('430', 'lbl_Filer', 'فائلر', 'ur-PK'),
('431', 'lbl_FilingCabinetsRequest', 'فائلنگ کابینہ کی درخواست', 'ur-PK'),
('432', 'lbl_FinalApprovalID', 'حتمی منظوری  نمبر', 'ur-PK'),
('433', 'lbl_Finance', 'مالیات', 'ur-PK'),
('434', 'lbl_FineArt', 'فائن آرٹ', 'ur-PK'),
('435', 'lbl_First', 'پہلا', 'ur-PK'),
('436', 'lbl_FirstName', 'پہلا نام', 'ur-PK'),
('437', 'lbl_FirstQuotationAmount', 'پہلی نرخ کی رقم', 'ur-PK'),
('438', 'lbl_FirstQuotationID', 'پہلی نرخ کی شناخت', 'ur-PK'),
('439', 'lbl_FirstQuotationPrice', 'پہلی نرخ کی قیمت', 'ur-PK'),
('440', 'lbl_FirstVendor', 'پہلا فروخت کنندہ', 'ur-PK'),
('441', 'lbl_Five', 'کھاتپانچواںے کا سربراہ', 'ur-PK'),
('442', 'lbl_Fixed', 'مقررہ', 'ur-PK'),
('443', 'lbl_FixedDeducationDetails', 'مقررہ کٹوتی کی تفصیلات', 'ur-PK'),
('444', 'lbl_FixedDeduction', 'مقررہ کٹوتی', 'ur-PK'),
('445', 'lbl_FixedDeductionApproval', 'مقررہ کٹوتی کی منظوری', 'ur-PK'),
('446', 'lbl_FixedDeductionDetails', 'مقررہ کٹوتی کی تفصیل', 'ur-PK'),
('447', 'lbl_FixedDeductionID', 'مقررہ کٹوتی نمبر', 'ur-PK'),
('448', 'lbl_FixedDeductionList', 'مقررہ کٹوتیوں کی فہرست', 'ur-PK'),
('449', 'lbl_FlexibleDutyHoursAllowed', 'اجازت شدہ لچکدار ڈیوٹی کے اوقات', 'ur-PK'),
('450', 'lbl_FlexibleDutyManagement', 'لچکدار ڈیوٹی کا نظم', 'ur-PK'),
('451', 'lbl_Football', 'فٹبال', 'ur-PK'),
('452', 'lbl_FootrestRequest', 'فٹ ریسٹ کی درخواست', 'ur-PK'),
('453', 'lbl_ForgotPassword', 'پاس ورڈ بھول گئے', 'ur-PK'),
('454', 'lbl_FortheMonthof', 'کے مہینے کے لیے', 'ur-PK'),
('455', 'lbl_FortheYearof', 'کے سال کے لیے', 'ur-PK'),
('456', 'lbl_Forward', 'آگے بھیجنا', 'ur-PK'),
('457', 'lbl_ForwardCostComparison', 'لاگت کا موازنہ آگے بھیجیں', 'ur-PK'),
('458', 'lbl_ForwordRequestForQuotation', 'درخواست برائے نرخ آگے بھیجیں', 'ur-PK'),
('459', 'lbl_Four', 'چوتھا', 'ur-PK'),
('460', 'lbl_FromChequeNo', 'چیک نمبر سے', 'ur-PK'),
('461', 'lbl_FromDate', 'شروع کی تاریخ', 'ur-PK'),
('462', 'lbl_FromDutySlot', 'ڈیوٹی سلاٹ سے', 'ur-PK'),
('463', 'lbl_FullName', 'مکمل نام', 'ur-PK'),
('464', 'lbl_Gender', 'جنس', 'ur-PK'),
('465', 'lbl_GeneralSettings', 'عمومی ترتیبات', 'ur-PK'),
('466', 'lbl_GlobalSettings', 'عالمی ترتیبات', 'ur-PK'),
('467', 'lbl_GotoAttendance', 'حاضری پر جائیں', 'ur-PK'),
('468', 'lbl_GotoEmployeeLogin', 'ملازم لاگ اِن پر جائیں', 'ur-PK'),
('469', 'lbl_GotoSupplierLogin', 'سپلائر لاگ اِن پر جائیں', 'ur-PK'),
('470', 'lbl_GotoUserLogin', 'صارف لاگ اِن پر جائیں', 'ur-PK'),
('471', 'lbl_GRNNo', 'جی آر این نمبر', 'ur-PK'),
('472', 'lbl_GrossSalary', 'مجموعی تنخواہ', 'ur-PK'),
('473', 'lbl_HasLotNumberandExpiryDate', 'لاٹ نمبر اور اختتامی تاریخ موجود ہے', 'ur-PK'),
('474', 'lbl_HeadofAccount', 'کھاتے کا سربراہ', 'ur-PK'),
('475', 'lbl_HeadofAccount(Credit)', 'ہیڈ آف اکاؤنٹ (کریڈٹ)', 'ur-PK'),
('476', 'lbl_HeadofAccount(Debit)', 'ہیڈ آف اکاؤنٹ (ڈیبٹ)', 'ur-PK'),
('477', 'lbl_HeadofAccountFirst', 'پہلا ہیڈ آف اکاؤنٹ', 'ur-PK'),
('478', 'lbl_HeadofAccountFirstID', 'پہلا ہیڈ آف اکاؤنٹ نمبر', 'ur-PK'),
('479', 'lbl_HeadofAccountFirstList', 'ہیڈ آف اکاؤنٹ فرسٹ کی فہرست', 'ur-PK'),
('480', 'lbl_HeadofAccountFirstName', 'پہلا ہیڈ آف اکاؤنٹ کا نام', 'ur-PK'),
('481', 'lbl_HeadofAccountFive', 'پانچواں ہیڈ آف اکاؤنٹ', 'ur-PK'),
('482', 'lbl_HeadofAccountFiveID', 'پانچواں ہیڈ آف اکاؤنٹ نمبر', 'ur-PK'),
('483', 'lbl_HeadofAccountFiveList', 'ہیڈ آف اکاؤنٹ فائیو کی فہرست', 'ur-PK'),
('484', 'lbl_HeadofAccountFiveName', 'پانچواں ہیڈ آف اکاؤنٹ کا نام', 'ur-PK'),
('485', 'lbl_HeadofAccountFour', 'چوتھا ہیڈ آف اکاؤنٹ', 'ur-PK'),
('486', 'lbl_HeadofAccountFourID', 'چوتھا ہیڈ آف اکاؤنٹ نمبر', 'ur-PK'),
('487', 'lbl_HeadofAccountFourList', 'ہیڈ آف اکاؤنٹ فور کی فہرست', 'ur-PK'),
('488', 'lbl_HeadofAccountFourName', 'چوتھا ہیڈ آف اکاؤنٹ کا نام', 'ur-PK'),
('489', 'lbl_HeadofAccountSecond', 'دوسرا ہیڈ آف اکاؤنٹ', 'ur-PK'),
('490', 'lbl_HeadofAccountSecondID', 'دوسرا ہیڈ آف اکاؤنٹ نمبر', 'ur-PK'),
('491', 'lbl_HeadofAccountSecondList', 'ہیڈ آف اکاؤنٹ سیکنڈ کی فہرست', 'ur-PK'),
('492', 'lbl_HeadofAccountSecondName', 'دوسرا ہیڈ آف اکاؤنٹ کا نام', 'ur-PK'),
('493', 'lbl_HeadofAccountThird', 'تیسرا ہیڈ آف اکاؤنٹ', 'ur-PK'),
('494', 'lbl_HeadofAccountThirdID', 'تیسرا ہیڈ آف اکاؤنٹ نمبر', 'ur-PK'),
('495', 'lbl_HeadofAccountThirdList', 'ہیڈ آف اکاؤنٹ تھرڈ کی فہرست', 'ur-PK'),
('496', 'lbl_HeadofAccountThirdName', 'تیسرا ہیڈ آف اکاؤنٹ کا نام', 'ur-PK'),
('497', 'lbl_HeadsetwithMicrophoneRequest', 'ہیڈ سیٹ مائیکروفون کے ساتھ کی درخواست', 'ur-PK'),
('498', 'lbl_Help', 'مدد', 'ur-PK'),
('499', 'lbl_Here', 'یہاں', 'ur-PK'),
('500', 'lbl_HireDate', 'پاسپورٹ میعاد ختم ہونے کی تاریخ', 'ur-PK'),
('501', 'lbl_Holiday', 'تعطیل', 'ur-PK'),
('502', 'lbl_HolidayDate', 'تعطیل کی تاریخ', 'ur-PK'),
('503', 'lbl_HolidayList', 'تعطیلات کی فہرست', 'ur-PK'),
('504', 'lbl_HolidayType', 'تعطیل کی قسم', 'ur-PK'),
('505', 'lbl_HolidayTypeID', 'تعطیل کی قسم  نمبر', 'ur-PK'),
('506', 'lbl_HolidayTypeList', 'تعطیل کی قسم  کی فہرست', 'ur-PK'),
('507', 'lbl_HolidayTypeName', 'تعطیل کی قسم  کا نام', 'ur-PK'),
('508', 'lbl_HourlySalarySheet', 'گھنٹوں کی تنخواہ شیٹ', 'ur-PK'),
('509', 'lbl_HR', 'انسانی وسائل', 'ur-PK'),
('510', 'lbl_HumanResources', 'انسانی وسائل', 'ur-PK'),
('511', 'lbl_ID', 'نمبر', 'ur-PK'),
('512', 'lbl_IDExpiryDate', 'شناختی کارڈ میعاد ختم ہونے کی تاریخ', 'ur-PK'),
('513', 'lbl_IDInfomation', 'شناختی معلومات', 'ur-PK'),
('514', 'lbl_IDIssueDate', 'شناختی کارڈ اجراء کی تاریخ', 'ur-PK'),
('515', 'lbl_IDNumber', 'شناختی نمبر', 'ur-PK'),
('516', 'lbl_IDPlaceofIssue', 'شناختی نمبر اجراء کی جگہ', 'ur-PK'),
('517', 'lbl_Income', 'آمدنی', 'ur-PK'),
('518', 'lbl_IncomeSheet', 'آمدنی شیٹ', 'ur-PK'),
('519', 'lbl_IncomeSheetPrint', 'آمدنی شیٹ پرنٹ', 'ur-PK'),
('520', 'lbl_IncomeSheetReport', 'آمدنی شیٹ رپورٹ', 'ur-PK'),
('521', 'lbl_IncomeTax(Withholding)', 'آمدنی ٹیکس (وِد ہولڈنگ)', 'ur-PK'),
('522', 'lbl_IncomeTaxDetail', 'انکم ٹیکس کی تفصیل', 'ur-PK'),
('523', 'lbl_Institute', 'ادارہ', 'ur-PK'),
('524', 'lbl_InstrumentAmount', 'انسٹرومنٹ کی رقم', 'ur-PK'),
('525', 'lbl_InstrumentDate', 'انسٹرومنٹ کی تاریخ', 'ur-PK'),
('526', 'lbl_InstrumentDetail', 'انسٹرومنٹ کی تفصیل', 'ur-PK'),
('527', 'lbl_InstrumentNumber', 'انسٹرومنٹ نمبر', 'ur-PK'),
('528', 'lbl_InstrumentType', 'انسٹرومنٹ کی قسم', 'ur-PK'),
('529', 'lbl_InTime', 'حاضری وقت', 'ur-PK'),
('530', 'lbl_InvoiceNo', 'انوائس نمبر', 'ur-PK'),
('531', 'lbl_IssuanceDate', 'اجرا کی تاریخ', 'ur-PK'),
('532', 'lbl_IssuanceNo', 'اجرا نمبر', 'ur-PK'),
('533', 'lbl_IssuanceQuantity', 'جاری کردہ مقدار', 'ur-PK'),
('534', 'lbl_IssuanceStatus', 'اجرا کی حیثیت', 'ur-PK'),
('535', 'lbl_IssueDate', 'اجراء کی تاریخ', 'ur-PK'),
('536', 'lbl_Item', 'آئٹم', 'ur-PK'),
('537', 'lbl_ItemCategoryType', 'آئٹم کیٹیگری کی قسم', 'ur-PK'),
('538', 'lbl_ItemCategoryTypeID', 'آئٹم کیٹیگری قسم نمبر', 'ur-PK'),
('539', 'lbl_ItemCategoryTypeList', 'آئٹم کیٹیگری قسم کی فہرست', 'ur-PK'),
('540', 'lbl_ItemCategoryTypeName', 'آئٹم کیٹیگری قسم کا نام', 'ur-PK'),
('541', 'lbl_ItemCode', 'آئٹم کوڈ', 'ur-PK'),
('542', 'lbl_ItemComponentType', 'آئٹم جزو کی قسم', 'ur-PK'),
('543', 'lbl_ItemComponentTypeID', 'آئٹم جزو قسم شناختی نمبر', 'ur-PK'),
('544', 'lbl_ItemComponentTypeList', 'آئٹم جزو قسم کی فہرست', 'ur-PK'),
('545', 'lbl_ItemComponentTypeName', 'آئٹم جزو قسم کا نام', 'ur-PK'),
('546', 'lbl_ItemID', 'آئٹم نمبر', 'ur-PK'),
('547', 'lbl_ItemList', 'آئٹم کی فہرست', 'ur-PK'),
('548', 'lbl_ItemName', 'آئٹم کا نام', 'ur-PK'),
('549', 'lbl_ItemUnitType', 'آئٹم یونٹ کی قسم', 'ur-PK'),
('550', 'lbl_ItemUnitTypeCode', 'آئٹم یونٹ قسم کا کوڈ', 'ur-PK'),
('551', 'lbl_ItemUnitTypeID', 'آئٹم یونٹ قسم شناختی نمبر', 'ur-PK'),
('552', 'lbl_ItemUnitTypeList', 'آئٹم یونٹ قسم کی فہرست', 'ur-PK'),
('553', 'lbl_ItemUnitTypeName', 'آئٹم یونٹ قسم کا نام', 'ur-PK'),
('554', 'lbl_Jeans', 'جینز', 'ur-PK'),
('555', 'lbl_Joining', 'شمولیت', 'ur-PK'),
('556', 'lbl_JoiningDate', 'شمولیت کی تاریخ', 'ur-PK'),
('557', 'lbl_JoiningList', 'شمولیت کی فہرست', 'ur-PK'),
('558', 'lbl_JournalVoucher', 'جرنل واؤچر', 'ur-PK'),
('559', 'lbl_JournalVoucher', 'جرنل واؤچر', 'ur-PK'),
('560', 'lbl_JournalVoucherApproval', 'جرنل ووچر کی منظوری', 'ur-PK'),
('561', 'lbl_JournalVoucherList', 'جرنل واؤچر کی فہرست', 'ur-PK'),
('562', 'lbl_KeyboardRequest', 'کی بورڈ کی درخواست', 'ur-PK'),
('563', 'lbl_LANCardsRequest', 'ایل اے این کارڈز کی درخواست', 'ur-PK'),
('564', 'lbl_LaptopCoolingPadsRequest', 'لیپ ٹاپ کولنگ پیڈز کی درخواست', 'ur-PK'),
('565', 'lbl_LaptopsRequest', 'لیپ ٹاپ کی درخواست', 'ur-PK'),
('566', 'lbl_Late', 'تاخیر سے', 'ur-PK'),
('567', 'lbl_LateArrivalManagement', 'تاخیر سے آمد کا نظم', 'ur-PK'),
('568', 'lbl_LateComingDeduction(Hours)', 'دیر سے آنے کی کٹوتی (گھنٹے)', 'ur-PK'),
('569', 'lbl_LateComingHours', 'دیر سے آنے کے اوقات', 'ur-PK'),
('570', 'lbl_LateComingRequest', 'دیر سے آنے کی درخواست', 'ur-PK'),
('571', 'lbl_LateGoingAmount(Hours)', 'دیر سے جانے کی رقم (گھنٹے)', 'ur-PK'),
('572', 'lbl_LateGoingHours', 'دیر سے جانے کے اوقات', 'ur-PK'),
('573', 'lbl_LateStayOvertimeManagement', 'دیر سے رکنے پر اوور ٹائم کا نظم', 'ur-PK'),
('574', 'lbl_LEDRequest', 'ایل ای ڈی کی درخواست', 'ur-PK'),
('575', 'lbl_License', 'لائسنس', 'ur-PK'),
('576', 'lbl_List', 'فہرست', 'ur-PK'),
('577', 'lbl_Lodgement', 'جمع رقم', 'ur-PK'),
('578', 'lbl_LodgementPrint', 'جمع رقم پرنٹ', 'ur-PK'),
('579', 'lbl_LodgementReport', 'جمع رقم کی رپورٹ', 'ur-PK'),
('580', 'lbl_Login', 'لاگ اِن', 'ur-PK'),
('581', 'lbl_Login-Pages', 'لاگ اِن - صفحات', 'ur-PK'),
('582', 'lbl_LogOut', 'باہر نکلیں', 'ur-PK'),
('583', 'lbl_LotNumber', 'بیچ نمبر', 'ur-PK'),
('584', 'lbl_Main', 'مرکزی', 'ur-PK'),
('585', 'lbl_MakePurchaseOrder', 'خریداری کا آرڈر بنائیں', 'ur-PK'),
('586', 'lbl_Management', 'انتظامیہ', 'ur-PK'),
('587', 'lbl_Manufacturer', 'مینوفیکچرر', 'ur-PK'),
('588', 'lbl_ManufacturerType', 'مینوفیکچرر کی قسم', 'ur-PK'),
('589', 'lbl_ManufacturerTypeID', 'مینوفیکچرر قسم نمبر', 'ur-PK'),
('590', 'lbl_ManufacturerTypeList', 'مینوفیکچرر قسم کی فہرست', 'ur-PK'),
('591', 'lbl_ManufacturerTypeName', 'مینوفیکچرر قسم کا نام', 'ur-PK'),
('592', 'lbl_MaritalStatus', 'ازدواجی حیثیت', 'ur-PK'),
('593', 'lbl_MarkDate', 'مارک کی تاریخ', 'ur-PK'),
('594', 'lbl_Mastercard', 'ماسٹر کارڈ', 'ur-PK'),
('595', 'lbl_MasterInformation', 'ماسٹر معلومات', 'ur-PK'),
('596', 'lbl_MaterialIssuance', 'مواد جاری کرنا', 'ur-PK'),
('597', 'lbl_MaterialIssuanceList', 'مواد کے اجرا کی فہرست', 'ur-PK'),
('598', 'lbl_MaterialIssuancesForm', 'مواد کے اجرا کا فارم', 'ur-PK'),
('599', 'lbl_MaterialReceived', 'مواد وصول کیا گیا', 'ur-PK'),
('600', 'lbl_MaterialReceivedList', 'وصول شدہ مواد کی فہرست', 'ur-PK'),
('601', 'lbl_MaterialRequisition', 'مٹیریل کی درخواست', 'ur-PK'),
('602', 'lbl_MaterialRequisitionApproval', 'مواد کی طلب کی منظوری', 'ur-PK'),
('603', 'lbl_MaterialRequisitionForm', 'مٹیریل کی درخواست کا فارم', 'ur-PK'),
('604', 'lbl_MaterialRequisitionList', 'مٹیریل کی درخواستوں کی فہرست', 'ur-PK'),
('605', 'lbl_MeetingTablesRequest', 'میٹنگ ٹیبلز کی درخواست', 'ur-PK'),
('606', 'lbl_Mobile', 'موبائل', 'ur-PK'),
('607', 'lbl_ModemsRequest', 'موڈیمز کی درخواست', 'ur-PK'),
('608', 'lbl_MonitorsRequest', 'مانیٹرز کی درخواست', 'ur-PK'),
('609', 'lbl_Month', 'مہینہ', 'ur-PK'),
('610', 'lbl_MonthlyPayslip', 'ماہانہ پے سلپ', 'ur-PK'),
('611', 'lbl_MonthlySalarySheet', 'ماہانہ تنخواہ شیٹ', 'ur-PK'),
('612', 'lbl_MoreThemes', 'مزید تھیمز', 'ur-PK'),
('613', 'lbl_MousePadsRequest', 'ماؤس پیڈز کی درخواست', 'ur-PK'),
('614', 'lbl_MouseRequest', 'ماؤس کی درخواست', 'ur-PK'),
('615', 'lbl_My', 'میرا', 'ur-PK'),
('616', 'lbl_MyProfile', 'میری پروفائل', 'ur-PK'),
('617', 'lbl_N/A', 'دستیاب نہیں', 'ur-PK'),
('618', 'lbl_Name', 'نام', 'ur-PK'),
('619', 'lbl_Nature', 'نوعیت', 'ur-PK'),
('620', 'lbl_NetIncome', 'خالص آمدنی', 'ur-PK'),
('621', 'lbl_NewContractApproval', 'نئے معاہدے کی منظوری', 'ur-PK'),
('622', 'lbl_NewEmployeeApproval', 'نئے ملازم کی منظوری', 'ur-PK'),
('623', 'lbl_NewEndDate', 'نئی اختتام کی تاریخ', 'ur-PK'),
('624', 'lbl_NewPassword', 'نیا پاس ورڈ', 'ur-PK'),
('625', 'lbl_NewPurchaseRequest', 'نئی خریداری کی درخواست', 'ur-PK'),
('626', 'lbl_NewPurchaseRequestApproval', 'نئی خریداری کی درخواست کی منظوری', 'ur-PK'),
('627', 'lbl_NewSalaryApproval', 'نئی تنخواہ کی منظوری', 'ur-PK'),
('628', 'lbl_NewStartDate', 'نئی آغاز کی تاریخ', 'ur-PK'),
('629', 'lbl_NewUserApproval', 'نئے صارف کی منظوری', 'ur-PK'),
('630', 'lbl_No', 'نہیں', 'ur-PK'),
('631', 'lbl_Noadditionalallowancedataavailable.', 'کوئی اضافی الاؤنس کا ڈیٹا دستیاب نہیں۔', 'ur-PK'),
('632', 'lbl_Nodeductiondataavailable.', 'کوئی کٹوتی کا ڈیٹا دستیاب نہیں۔', 'ur-PK'),
('633', 'lbl_NoDocumentAvailable', 'کوئی دستاویز دستیاب نہیں', 'ur-PK'),
('634', 'lbl_NoofChildren', 'بچوں کی تعداد', 'ur-PK'),
('635', 'lbl_Noovertimedataavailable.', 'کوئی اوور ٹائم کا ڈیٹا دستیاب نہیں۔', 'ur-PK'),
('636', 'lbl_Note', 'مثالیں', 'ur-PK'),
('637', 'lbl_Notebooks/StickyNotesRequest', 'نوٹ بکس/چپچپے نوٹس کی درخواست', 'ur-PK'),
('638', 'lbl_Notification', 'اطلاع', 'ur-PK'),
('639', 'lbl_NotSet', 'مقرر نہیں', 'ur-PK'),
('640', 'lbl_NTN', 'این ٹی این', 'ur-PK'),
('641', 'lbl_NTNRate', 'این ٹی این شرح', 'ur-PK'),
('642', 'lbl_NumberofDays', 'دنوں کی تعداد', 'ur-PK'),
('643', 'lbl_NumberofMonths', 'مہینوں کی تعداد', 'ur-PK'),
('644', 'lbl_NumberofWorkingDaysinaWeek', 'ہفتے میں کام کے دنوں کی تعداد', 'ur-PK'),
('645', 'lbl_NumberofYears', 'سالوں کی تعداد', 'ur-PK'),
('646', 'lbl_OfficeChairRequest', 'دفتر کی کرسی کی درخواست', 'ur-PK'),
('647', 'lbl_OfficeDeskRequest', 'دفتر کی میز کی درخواست', 'ur-PK'),
('648', 'lbl_OldPassword', 'پرانا پاس ورڈ', 'ur-PK'),
('649', 'lbl_OpeningBalance', 'ابتدائی بیلنس', 'ur-PK'),
('650', 'lbl_OrderDetail', 'آرڈر کی تفصیل', 'ur-PK'),
('651', 'lbl_OrderedFood', 'کھانا آرڈر کیا', 'ur-PK'),
('652', 'lbl_OrderStatistics', 'آرڈر کے اعداد و شمار', 'ur-PK'),
('653', 'lbl_OutTime', 'روانگی وقت', 'ur-PK'),
('654', 'lbl_Overtime', 'اوور ٹائم', 'ur-PK'),
('655', 'lbl_OvertimeApproval', 'اوور ٹائم کی منظوری', 'ur-PK'),
('656', 'lbl_OverTimeDetail', 'اوور ٹائم کی تفصیل', 'ur-PK'),
('657', 'lbl_OverTimeID', 'اوور ٹائم نمبر', 'ur-PK'),
('658', 'lbl_OverTimeList', 'اوور ٹائم کی فہرست', 'ur-PK'),
('659', 'lbl_OverTimePercentageofDailyPay', 'اوور ٹائم کا یومیہ تنخواہ میں فیصد', 'ur-PK'),
('660', 'lbl_OverTimeRate', 'اوور ٹائم کی شرح', 'ur-PK'),
('661', 'lbl_OverTimeRateID', 'اوور ٹائم شرح نمبر', 'ur-PK'),
('662', 'lbl_OverTimeRateList', 'اوور ٹائم شرح کی فہرست', 'ur-PK'),
('663', 'lbl_OverTimeRateValue', 'اوور ٹائم شرح کی قیمت', 'ur-PK'),
('664', 'lbl_OverTimeRequest', 'اوور ٹائم کی درخواست', 'ur-PK'),
('665', 'lbl_OverTimeType', 'اوور ٹائم کی قسم', 'ur-PK'),
('666', 'lbl_PassportExpiryDate', 'پاسپورٹ میعاد ختم ہونے کی تاریخ', 'ur-PK'),
('667', 'lbl_PassportInfomation', 'پاسپورٹ معلومات', 'ur-PK'),
('668', 'lbl_PassportIssueDate', 'پاسپورٹ اجراء کی تاریخ', 'ur-PK'),
('669', 'lbl_PassportNumber', 'پاسپورٹ نمبر', 'ur-PK'),
('670', 'lbl_PassportPlaceofIssue', 'پاسپورٹ اجراء کی جگہ', 'ur-PK'),
('671', 'lbl_Password', 'پاس ورڈ', 'ur-PK'),
('672', 'lbl_Payments', 'ادائیگیاں', 'ur-PK'),
('673', 'lbl_PaymentSection', 'ادائیگی سیکشن', 'ur-PK'),
('674', 'lbl_PaymentVoucher', 'ادائیگی واؤچر', 'ur-PK'),
('675', 'lbl_PaymentVoucher', 'ادائیگی واؤچر', 'ur-PK'),
('676', 'lbl_PaymentVoucherApproval', 'ادائیگی ووچر کی منظوری', 'ur-PK'),
('677', 'lbl_PaymentVoucherID', 'ادائیگی واؤچر نمبر', 'ur-PK'),
('678', 'lbl_PaymentVoucherList', 'ادائیگی واؤچر کی فہرست', 'ur-PK'),
('679', 'lbl_Paypal', 'پے پال', 'ur-PK'),
('680', 'lbl_PayRoll', 'پے رول', 'ur-PK'),
('681', 'lbl_PayRollApproval', 'پے رول کی منظوری', 'ur-PK'),
('682', 'lbl_PendingDate', 'التواء کی تاریخ', 'ur-PK'),
('683', 'lbl_PendingRequisitionsList', 'زیر التواء درخواستوں کی فہرست', 'ur-PK'),
('684', 'lbl_PenHolders&DeskOrganizersRequest', 'قلم ہولڈرز اور ڈیسک آرگنائزرز کی درخواست', 'ur-PK'),
('685', 'lbl_Pens/PencilsRequest', 'قلم/پنسل کی درخواست', 'ur-PK'),
('686', 'lbl_PerDayHours', 'فی دن اوقات', 'ur-PK'),
('687', 'lbl_PerDaySalary', 'یومیہ تنخواہ', 'ur-PK'),
('688', 'lbl_PersonName', 'فرد کا نام', 'ur-PK'),
('689', 'lbl_Phone', 'فون', 'ur-PK'),
('690', 'lbl_Phone1', 'فون نمبر 1', 'ur-PK'),
('691', 'lbl_Phone2', 'فون نمبر 2', 'ur-PK'),
('692', 'lbl_PhoneStandsRequest', 'فون اسٹینڈز کی درخواست', 'ur-PK'),
('693', 'lbl_Picture', 'تصویر', 'ur-PK'),
('694', 'lbl_PlaceofBirth', 'جائے پیدائش', 'ur-PK'),
('695', 'lbl_Pleaseselect', 'منتخب کریں', 'ur-PK'),
('696', 'lbl_Pleasesign-intoyouremployeeaccount.', 'براہِ کرم اپنے ملازم اکاؤنٹ میں سائن اِن کریں۔', 'ur-PK'),
('697', 'lbl_Pleasesign-intoyoursupplieraccount', 'براہ کرم اپنے سپلائر اکاؤنٹ میں سائن اِن کریں', 'ur-PK'),
('698', 'lbl_Pleasesign-intoyourUseraccount.', 'براہِ کرم اپنے صارف اکاؤنٹ میں سائن ان کریں۔', 'ur-PK'),
('699', 'lbl_POBox', 'پی او باکس', 'ur-PK'),
('700', 'lbl_PONo', 'پی او نمبر', 'ur-PK'),
('701', 'lbl_Portal', 'پورٹل', 'ur-PK'),
('702', 'lbl_Post', 'پوسٹ کریں', 'ur-PK'),
('703', 'lbl_Prefix', 'سابقہ', 'ur-PK'),
('704', 'lbl_PresentationPointer/ClickerRequest', 'پریزنٹیشن پوائنٹر/کلکر کی درخواست', 'ur-PK'),
('705', 'lbl_PresentTiming', 'موجودگی کا وقت', 'ur-PK'),
('706', 'lbl_PreviousEndDate', 'پچھلی اختتام کی تاریخ', 'ur-PK'),
('707', 'lbl_PreviousStartDate', 'پچھلی آغاز کی تاریخ', 'ur-PK'),
('708', 'lbl_Print', 'پرنٹ کریں', 'ur-PK'),
('709', 'lbl_PrintAccessRightsByRoleSetup', 'کردار کے لحاظ سے رسائی کی ترتیب کو پرنٹ کریں', 'ur-PK'),
('710', 'lbl_PrintAccessRightsByUserSetup', 'صارف کے لحاظ سے رسائی کی ترتیب کو پرنٹ کریں', 'ur-PK'),
('711', 'lbl_PrintAdditionalAllowanceType', ' اضافی الاؤنس کی قسم  پرنٹ کریں', 'ur-PK'),
('712', 'lbl_PrintApplicant', 'درخواست دہندہ پرنٹ کریں', 'ur-PK'),
('713', 'lbl_PrintBank', 'بینک پرنٹ کریں', 'ur-PK'),
('714', 'lbl_PrintBranch', 'برانچ پرنٹ کریں', 'ur-PK'),
('715', 'lbl_PrintCashAgainstSale', 'فروخت کے عوض نقد پرنٹ کریں', 'ur-PK'),
('716', 'lbl_PrintCategoryType', 'زمرہ کی قسم پرنٹ کریں', 'ur-PK'),
('717', 'lbl_PrintChequeBook', 'چیک بُک پرنٹ کریں', 'ur-PK'),
('718', 'lbl_PrintContract', 'معاہدہ پرنٹ کریں', 'ur-PK'),
('719', 'lbl_PrintDeduction', 'کٹوتی پرنٹ کریں', 'ur-PK'),
('720', 'lbl_PrintDeductionSetup', 'کٹوتی کی ترتیب  پرنٹ کریں', 'ur-PK'),
('721', 'lbl_PrintDeductionType', 'کٹوتی کی قسم  پرنٹ کریں', 'ur-PK'),
('722', 'lbl_PrintDepartment', 'شعبہ  پرنٹ کریں', 'ur-PK'),
('723', 'lbl_PrintDesignation', 'عہدہ  پرنٹ کریں', 'ur-PK'),
('724', 'lbl_PrintEmployeeRequest', 'ملازم درخواست پرنٹ کریں', 'ur-PK'),
('725', 'lbl_PrintEmployeeRequestType', 'ملازم درخواست کی قسم  پرنٹ کریں', 'ur-PK'),
('726', 'lbl_PrintEmployeeRequestTypeApprovalSetup', 'ملازم درخواست قسم منظوری سیٹ اپ پرنٹ کریں', 'ur-PK'),
('727', 'lbl_PrintEmployeeStatusType', 'ملازم حیثیت کی قسم  پرنٹ کریں', 'ur-PK'),
('728', 'lbl_PrintEndOfService', 'اختتامِ سروس پرنٹ کریں', 'ur-PK'),
('729', 'lbl_PrintersRequest', 'پرنٹرز کی درخواست', 'ur-PK'),
('730', 'lbl_PrintFaceAttendance', 'چہرے کی حاضری پرنٹ کریں', 'ur-PK'),
('731', 'lbl_PrintFixedDeduction', 'مقررہ کٹوتی پرنٹ کریں', 'ur-PK'),
('732', 'lbl_PrintHeadofAccountFirst', 'ہیڈ آف اکاؤنٹ فرسٹ پرنٹ کریں', 'ur-PK'),
('733', 'lbl_PrintHeadofAccountFive', 'ہیڈ آف اکاؤنٹ فائیو پرنٹ کریں', 'ur-PK'),
('734', 'lbl_PrintHeadofAccountFour', 'ہیڈ آف اکاؤنٹ فور پرنٹ کریں', 'ur-PK'),
('735', 'lbl_PrintHeadofAccountSecond', 'ہیڈ آف اکاؤنٹ سیکنڈ پرنٹ کریں', 'ur-PK'),
('736', 'lbl_PrintHeadofAccountThird', 'ہیڈ آف اکاؤنٹ تھرڈ پرنٹ کریں', 'ur-PK'),
('737', 'lbl_PrintHolidayType', 'تعطیل کی قسم  پرنٹ کریں', 'ur-PK'),
('738', 'lbl_PrintItem', 'آئٹم پرنٹ کریں', 'ur-PK'),
('739', 'lbl_PrintItemCategoryType', 'آئٹم کیٹیگری قسم پرنٹ کریں', 'ur-PK'),
('740', 'lbl_PrintItemComponentType', 'آئٹم جزو قسم پرنٹ کریں', 'ur-PK'),
('741', 'lbl_PrintItemUnitType', 'آئٹم یونٹ قسم پرنٹ کریں', 'ur-PK'),
('742', 'lbl_PrintJournalVoucher', 'جرنل واؤچر پرنٹ کریں', 'ur-PK'),
('743', 'lbl_PrintManufacturerType', 'مینوفیکچرر قسم پرنٹ کریں', 'ur-PK'),
('744', 'lbl_PrintMaterialIssuance', 'مواد کے اجرا کو پرنٹ کریں', 'ur-PK'),
('745', 'lbl_PrintMaterialRequisition', 'مٹیریل کی درخواست پرنٹ کریں', 'ur-PK'),
('746', 'lbl_PrintMonthlyPayslip', 'ماہانہ پے سلپ پرنٹ کریں', 'ur-PK'),
('747', 'lbl_PrintMonthlySalarySheet', 'ماہانہ تنخواہ شیٹ پرنٹ کریں', 'ur-PK'),
('748', 'lbl_PrintOverTime', 'اوور ٹائم پرنٹ کریں', 'ur-PK'),
('749', 'lbl_PrintOverTimeRate', 'اوور ٹائم شرح پرنٹ کریں', 'ur-PK'),
('750', 'lbl_PrintPaymentVoucher', 'ادائیگی واؤچر پرنٹ کریں', 'ur-PK'),
('751', 'lbl_PrintProcessType', 'عمل کی قسم  پرنٹ کریں', 'ur-PK'),
('752', 'lbl_PrintProcessTypeApprovalSetup', 'عمل کی قسم منظوری سیٹ اپ پرنٹ کریں', 'ur-PK'),
('753', 'lbl_PrintPurchaseOrder', 'خریداری کے آرڈر کا پرنٹ نکالیں', 'ur-PK'),
('754', 'lbl_PrintPurchaseRequest', 'خریداری کی درخواست پرنٹ کریں', 'ur-PK'),
('755', 'lbl_PrintQualification', 'اہلیت  پرنٹ کریں', 'ur-PK'),
('756', 'lbl_PrintReceivedVoucher', 'وصولی واؤچر پرنٹ کریں', 'ur-PK'),
('757', 'lbl_PrintRequestForQuotation', 'درخواست برائے نرخ پرنٹ کریں', 'ur-PK'),
('758', 'lbl_PrintRoleType', 'صارف کردار کی قسم  پرنٹ کریں', 'ur-PK'),
('759', 'lbl_PrintSalaryType', 'تنخواہ کی قسم  پرنٹ کریں', 'ur-PK'),
('760', 'lbl_PrintSection', 'قطعہ  پرنٹ کریں', 'ur-PK'),
('761', 'lbl_PrintStock', 'اسٹاک پرنٹ کریں', 'ur-PK'),
('762', 'lbl_PrintSubQualification', 'ضمنی اہلیت  پرنٹ کریں', 'ur-PK'),
('763', 'lbl_PrintTransferVoucher', 'ٹرانسفر واؤچر پرنٹ کریں', 'ur-PK'),
('764', 'lbl_PrintUser', 'صارف  پرنٹ کریں', 'ur-PK'),
('765', 'lbl_PrintVacation', 'چھٹی پرنٹ کریں', 'ur-PK'),
('766', 'lbl_PrintVacationSettle', 'چھٹی کی ادائیگی پرنٹ کریں', 'ur-PK'),
('767', 'lbl_PrintVacationType', 'چھٹی کی قسم  پرنٹ کریں', 'ur-PK'),
('768', 'lbl_PrintVendor', 'سپلائر پرنٹ کریں', 'ur-PK'),
('769', 'lbl_PrintVoucherType', 'ووچر کی قسم پرنٹ کریں', 'ur-PK'),
('770', 'lbl_PrintWorkDay', 'ورک ڈے پرنٹ کریں', 'ur-PK'),
('771', 'lbl_PriorityLevel', 'ترجیح کی سطح', 'ur-PK'),
('772', 'lbl_ProcessApprovalDetail', 'عمل کی منظوری کی تفصیل', 'ur-PK'),
('773', 'lbl_ProcessApprovals', 'عمل کی منظوری', 'ur-PK'),
('774', 'lbl_ProcessApprovalsList', 'عمل کی منظوری کی فہرست', 'ur-PK'),
('775', 'lbl_ProcessType', 'عمل کی قسم', 'ur-PK'),
('776', 'lbl_ProcessTypeApprovalSetup', 'عمل کی قسم منظوری سیٹ اپ', 'ur-PK'),
('777', 'lbl_ProcessTypeApprovalSetup', 'عمل کی قسم منظوری سیٹ اپ', 'ur-PK'),
('778', 'lbl_ProcessTypeApprovalSetupID', 'عمل کی قسم منظوری سیٹ اپ نمبر', 'ur-PK'),
('779', 'lbl_ProcessTypeApprovalSetupList', 'عمل کی قسم منظوری سیٹ اپ کی فہرست', 'ur-PK'),
('780', 'lbl_ProcessTypeForward', 'عمل کی قسم فارورڈ کریں', 'ur-PK'),
('781', 'lbl_ProcessTypeForwardList', 'عمل کی قسم فارورڈ کی فہرست', 'ur-PK'),
('782', 'lbl_ProcessTypeID', 'عمل کی قسم  نمبر', 'ur-PK'),
('783', 'lbl_ProcessTypeList', 'عمل کی قسم  کی فہرست', 'ur-PK'),
('784', 'lbl_ProcessTypeName', 'عمل کی قسم  کا نام', 'ur-PK'),
('785', 'lbl_ProcurementQueue', 'سپلائی کا قطار نظام', 'ur-PK'),
('786', 'lbl_ProcurementQueueList', 'سپلائی قطار کی فہرست', 'ur-PK'),
('787', 'lbl_ProcurementQueueNo', 'سپلائی قطار نمبر', 'ur-PK'),
('788', 'lbl_Profile', 'پروفائل', 'ur-PK'),
('789', 'lbl_ProfileReport', 'پروفائل رپورٹ', 'ur-PK'),
('790', 'lbl_Profit', 'منافع', 'ur-PK'),
('791', 'lbl_ProjectorRequest', 'پروجیکٹر کی درخواست', 'ur-PK'),
('792', 'lbl_Province', 'صوبہ', 'ur-PK'),
('793', 'lbl_Purchase', 'خریداری', 'ur-PK'),
('794', 'lbl_PurchaseOrder', 'خریداری کا آرڈر', 'ur-PK'),
('795', 'lbl_PurchaseOrderApproval', 'خریداری آرڈر کی منظوری', 'ur-PK'),
('796', 'lbl_PurchaseOrderList', 'خریداری کے آرڈرز کی فہرست', 'ur-PK'),
('797', 'lbl_PurchaseRequest', 'خریداری کی درخواست', 'ur-PK'),
('798', 'lbl_PurchaseRequestForm', 'خریداری کی درخواست فارم', 'ur-PK'),
('799', 'lbl_PurchaseRequestList', 'خریداری درخواستوں کی فہرست', 'ur-PK'),
('800', 'lbl_PurchaseRequestStatus', 'خریداری درخواست کی حیثیت', 'ur-PK'),
('801', 'lbl_Qualification', 'اہلیت', 'ur-PK'),
('802', 'lbl_QualificationID', 'اہلیت  نمبر', 'ur-PK'),
('803', 'lbl_QualificationList', 'اہلیت  کی فہرست', 'ur-PK'),
('804', 'lbl_QualificationName', 'اہلیت  کا نام', 'ur-PK'),
('805', 'lbl_Quantity', 'مقدار', 'ur-PK'),
('806', 'lbl_Rank', 'درجہ', 'ur-PK'),
('807', 'lbl_Reason', 'وجہ', 'ur-PK'),
('808', 'lbl_ReasonType', 'وجہ کی قسم', 'ur-PK'),
('809', 'lbl_ReceivedDate', 'وصولی کی تاریخ', 'ur-PK'),
('810', 'lbl_ReceivedFrom', 'وصول کنندہ', 'ur-PK'),
('811', 'lbl_ReceivedNo', 'وصولی نمبر', 'ur-PK'),
('812', 'lbl_ReceivedVoucher', 'وصولی واؤچر', 'ur-PK'),
('813', 'lbl_ReceivedVoucher', 'وصولی واؤچر', 'ur-PK'),
('814', 'lbl_ReceivedVoucherApproval', 'موصولہ ووچر کی منظوری', 'ur-PK'),
('815', 'lbl_ReceivedVoucherID', 'وصولی واؤچر نمبر', 'ur-PK'),
('816', 'lbl_ReceivedVoucherList', 'وصولی واؤچر کی فہرست', 'ur-PK'),
('817', 'lbl_ReceptionDeskRequest', 'ریسپشن ڈیسک کی درخواست', 'ur-PK'),
('818', 'lbl_RecommendedVendor', 'تجویز کردہ فروشندہ', 'ur-PK'),
('819', 'lbl_RecorderLevelMax', 'ریکارڈر لیول زیادہ سے زیادہ', 'ur-PK'),
('820', 'lbl_RecorderLevelMin', 'ریکارڈر لیول کم از کم', 'ur-PK'),
('821', 'lbl_Refresh', 'تازہ کریں', 'ur-PK'),
('822', 'lbl_Refund', 'ریفنڈ', 'ur-PK'),
('823', 'lbl_ReimbursementRequest', 'رقم کی واپسی کی درخواست', 'ur-PK'),
('824', 'lbl_Reject', 'مسترد کریں', 'ur-PK'),
('825', 'lbl_Religion', 'مذہب', 'ur-PK'),
('826', 'lbl_RemainingEndDays', 'باقی اختتامی دن', 'ur-PK'),
('827', 'lbl_Remarks', 'تبصرے', 'ur-PK'),
('828', 'lbl_RememberMe', 'مجھے یاد رکھیں', 'ur-PK'),
('829', 'lbl_Remove', 'ہٹائیں', 'ur-PK'),
('830', 'lbl_Renewal', 'تجدید', 'ur-PK'),
('831', 'lbl_Reports', 'مراسلات', 'ur-PK'),
('832', 'lbl_Request', 'عرضی', 'ur-PK'),
('833', 'lbl_RequestDate', 'درخواست کی تاریخ', 'ur-PK'),
('834', 'lbl_RequestForQuotation', 'درخواست برائے نرخ', 'ur-PK'),
('835', 'lbl_RequestForQuotationList', 'درخواست برائے نرخ کی فہرست', 'ur-PK'),
('836', 'lbl_RequestForQuotationsForm', 'درخواست برائے نرخ کا فارم', 'ur-PK'),
('837', 'lbl_RequestNo', 'درخواست نمبر', 'ur-PK'),
('838', 'lbl_RequiredDate', 'ضروری تاریخ', 'ur-PK'),
('839', 'lbl_RequisitionDate', 'درخواست کی تاریخ', 'ur-PK'),
('840', 'lbl_RequisitionNo', 'درخواست نمبر', 'ur-PK'),
('841', 'lbl_RequisitionQuantity', 'درخواست کردہ مقدار', 'ur-PK'),
('842', 'lbl_RequisitionStatus', 'درخواست کی حیثیت', 'ur-PK'),
('843', 'lbl_Revenues', 'آمدنیاں', 'ur-PK'),
('844', 'lbl_Role', 'کردار', 'ur-PK'),
('845', 'lbl_RoleType', 'صارف کردار کی قسم', 'ur-PK'),
('846', 'lbl_RoleTypeID', 'صارف کردار کی قسم  نمبر', 'ur-PK'),
('847', 'lbl_RoleTypeList', 'صارف کردار کی قسم  کی فہرست', 'ur-PK'),
('848', 'lbl_RoleTypeName', 'صارف کردار کی قسم  کا نام', 'ur-PK'),
('849', 'lbl_RotationalShift/ShiftSwappingRequest', 'روٹیشنل شفٹ/شفٹ تبدیلی کی درخواست', 'ur-PK'),
('850', 'lbl_Salary', 'تنخواہ', 'ur-PK'),
('851', 'lbl_Salary', 'تنخواہ', 'ur-PK'),
('852', 'lbl_SalaryDetails', 'تنخواہ کی تفصیلات', 'ur-PK'),
('853', 'lbl_SalaryList', 'تنخواہوں کی فہرست', 'ur-PK'),
('854', 'lbl_SalarySheetDetail', 'تنخواہ شیٹ کی تفصیل', 'ur-PK'),
('855', 'lbl_SalarySlip', 'تنخواہ سلپ', 'ur-PK'),
('856', 'lbl_SalaryType', 'تنخواہ کی قسم', 'ur-PK'),
('857', 'lbl_SalaryTypeID', 'تنخواہ کی قسم  نمبر', 'ur-PK'),
('858', 'lbl_SalaryTypeList', 'تنخواہ کی قسم  کی فہرست', 'ur-PK'),
('859', 'lbl_SalaryTypeName', 'تنخواہ کی قسم  کا نام', 'ur-PK'),
('860', 'lbl_Sales', 'فروخت', 'ur-PK'),
('861', 'lbl_SaleTax', 'سیلز ٹیکس', 'ur-PK'),
('862', 'lbl_SaleTaxAccount', 'سیلز ٹیکس اکاؤنٹ', 'ur-PK'),
('863', 'lbl_SaleTaxDetail', 'سیلز ٹیکس کی تفصیل', 'ur-PK'),
('864', 'lbl_Save', 'محفوظ', 'ur-PK'),
('865', 'lbl_SaveChanges', 'تبدیلیاں محفوظ کریں', 'ur-PK'),
('866', 'lbl_SaveVoucher', 'واؤچر محفوظ کریں', 'ur-PK'),
('867', 'lbl_ScannersRequest', 'اسکینرز کی درخواست', 'ur-PK'),
('868', 'lbl_Search', ' تلاش', 'ur-PK'),
('869', 'lbl_SearchAdditionalAllowanceTypeName', ' اضافی الاؤنس کی قسم  کا نام تلاش کریں', 'ur-PK'),
('870', 'lbl_SearchBankName', 'بینک کا نام تلاش کریں', 'ur-PK'),
('871', 'lbl_SearchBranchName', 'برانچ کا نام تلاش کریں', 'ur-PK'),
('872', 'lbl_SearchCashAgainstSaleName', 'فروخت کے عوض نقد نام تلاش کریں', 'ur-PK'),
('873', 'lbl_SearchCategoryTypeName', 'زمرہ کی قسم کا نام تلاش کریں', 'ur-PK'),
('874', 'lbl_SearchDeductionSetupName', 'کٹوتی کی ترتیب  کا نام تلاش کریں', 'ur-PK'),
('875', 'lbl_SearchDeductionTypeName', 'کٹوتی کی قسم  کا نام تلاش کریں', 'ur-PK'),
('876', 'lbl_SearchDepartmentName', 'شعبہ  کا نام تلاش کریں', 'ur-PK'),
('877', 'lbl_SearchDesignationName', 'عہدہ  کا نام تلاش کریں', 'ur-PK'),
('878', 'lbl_SearchEmployee', 'ملازم تلاش کریں', 'ur-PK'),
('879', 'lbl_SearchEmployeeRequestTypeName', 'ملازم درخواست کی قسم  کا نام تلاش کریں', 'ur-PK'),
('880', 'lbl_SearchEmployeeStatusTypeName', 'ملازم حیثیت کی قسم  کا نام تلاش کریں', 'ur-PK'),
('881', 'lbl_SearchHeadofAccountFirstName', 'ہیڈ آف اکاؤنٹ فرسٹ نام تلاش کریں', 'ur-PK'),
('882', 'lbl_SearchHeadofAccountFiveName', 'ہیڈ آف اکاؤنٹ فائیو نام تلاش کریں', 'ur-PK'),
('883', 'lbl_SearchHeadofAccountFourName', 'ہیڈ آف اکاؤنٹ فور نام تلاش کریں', 'ur-PK'),
('884', 'lbl_SearchHeadofAccountName', 'اکاؤنٹ ہیڈ کا نام تلاش کریں', 'ur-PK'),
('885', 'lbl_SearchHeadofAccountSecondName', 'ہیڈ آف اکاؤنٹ سیکنڈ نام تلاش کریں', 'ur-PK'),
('886', 'lbl_SearchHeadofAccountThirdName', 'ہیڈ آف اکاؤنٹ تھرڈ نام تلاش کریں', 'ur-PK'),
('887', 'lbl_SearchHolidayTypeName', 'تعطیل کی قسم  کا نام تلاش کریں', 'ur-PK'),
('888', 'lbl_SearchingBox', 'تلاش خانہ', 'ur-PK'),
('889', 'lbl_SearchItemCategoryTypeName', 'آئٹم کیٹیگری قسم کے نام کی تلاش کریں', 'ur-PK'),
('890', 'lbl_SearchItemComponentTypeName', 'آئٹم جزو قسم کے نام کی تلاش کریں', 'ur-PK'),
('891', 'lbl_SearchItemName', 'آئٹم کے نام کی تلاش کریں', 'ur-PK'),
('892', 'lbl_SearchItemUnitTypeName', 'آئٹم یونٹ قسم کے نام کی تلاش کریں', 'ur-PK'),
('893', 'lbl_SearchManufacturerTypeName', 'مینوفیکچرر قسم کے نام کی تلاش کریں', 'ur-PK'),
('894', 'lbl_SearchOverTimeRate', 'اوور ٹائم شرح تلاش کریں', 'ur-PK'),
('895', 'lbl_SearchProcessTypeName', 'عمل کی قسم  کا نام تلاش کریں', 'ur-PK'),
('896', 'lbl_SearchQualificationName', 'اہلیت  کا نام تلاش کریں', 'ur-PK'),
('897', 'lbl_SearchRoleTypeName', 'صارف کردار کی قسم  کا نام تلاش کریں', 'ur-PK'),
('898', 'lbl_SearchSalaryTypeName', 'تنخواہ کی قسم  کا نام تلاش کریں', 'ur-PK'),
('899', 'lbl_SearchSectionName', 'قطعہ  کا نام تلاش کریں', 'ur-PK'),
('900', 'lbl_SearchSubQualificationName', 'ضمنی اہلیت  کا نام تلاش کریں', 'ur-PK'),
('901', 'lbl_SearchUserName', 'صارف  کا نام تلاش کریں', 'ur-PK'),
('902', 'lbl_SearchVacationTypeName', 'چھٹی کی قسم  کا نام تلاش کریں', 'ur-PK'),
('903', 'lbl_SearchVendorName', 'سپلائر کا نام تلاش کریں', 'ur-PK'),
('904', 'lbl_SearchVoucherTypeName', 'ووچر کی قسم کا نام تلاش کریں', 'ur-PK'),
('905', 'lbl_Second', 'دوسرا', 'ur-PK'),
('906', 'lbl_SecondQuotationAmount', 'دوسری نرخ کی رقم', 'ur-PK'),
('907', 'lbl_SecondQuotationID', 'دوسری نرخ کی شناخت', 'ur-PK'),
('908', 'lbl_SecondQuotationPrice', 'دوسری نرخ کی قیمت', 'ur-PK'),
('909', 'lbl_SecondVendor', 'دوسرا فروخت کنندہ', 'ur-PK'),
('910', 'lbl_Section', 'قطعہ', 'ur-PK'),
('911', 'lbl_SectionID', 'قطعہ  نمبر', 'ur-PK'),
('912', 'lbl_SectionList', 'قطعہ  کی فہرست', 'ur-PK'),
('913', 'lbl_SectionName', 'قطعہ  کا نام', 'ur-PK'),
('914', 'lbl_Select', 'انتخاب', 'ur-PK'),
('915', 'lbl_SelectAll', 'سب کو منتخب کریں', 'ur-PK'),
('916', 'lbl_SelectBranch', 'برانچ منتخب کریں', 'ur-PK'),
('917', 'lbl_SelectCashAgianstSaleAccount', 'فروخت کے عوض نقد اکاؤنٹ منتخب کریں', 'ur-PK'),
('918', 'lbl_SelectCategoryType', 'کیٹیگری کی قسم منتخب کریں', 'ur-PK'),
('919', 'lbl_SelectComparisonPassedVendor', 'منتخب شدہ فروخت کنندہ منتخب کریں', 'ur-PK'),
('920', 'lbl_SelectEmployee', 'ملازم منتخب کریں', 'ur-PK'),
('921', 'lbl_SelectFirstVendor', 'پہلا فروخت کنندہ منتخب کریں', 'ur-PK'),
('922', 'lbl_SelectGroup', 'گروپ منتخب کریں', 'ur-PK'),
('923', 'lbl_SelectHeadofAccount', 'ہیڈ آف اکاؤنٹ منتخب کریں', 'ur-PK'),
('924', 'lbl_SelectItem', 'آئٹم منتخب کریں', 'ur-PK'),
('925', 'lbl_SelectItemCategoryTypeName', 'آئٹم کیٹیگری قسم کا نام منتخب کریں', 'ur-PK'),
('926', 'lbl_SelectItemComponentDataType', 'آئٹم جزو ڈیٹا قسم منتخب کریں', 'ur-PK'),
('927', 'lbl_SelectItemFromProcurementQueue', 'سپلائی قطار سے آئٹم منتخب کریں', 'ur-PK'),
('928', 'lbl_SelectMonth', 'مہینہ منتخب کریں', 'ur-PK'),
('929', 'lbl_SelectNone', 'کچھ بھی منتخب نہ کریں', 'ur-PK'),
('930', 'lbl_SelectOption', 'اختیار منتخب کریں', 'ur-PK'),
('931', 'lbl_SelectPriorityLevel', 'ترجیح کی سطح منتخب کریں', 'ur-PK'),
('932', 'lbl_SelectRoleType', 'صارف کردار کی قسم منتخب کریں', 'ur-PK'),
('933', 'lbl_SelectSecondVendor', 'دوسرا فروخت کنندہ منتخب کریں', 'ur-PK'),
('934', 'lbl_SelectThirdVendor', 'تیسرا فروخت کنندہ منتخب کریں', 'ur-PK'),
('935', 'lbl_SelectTransactionType', 'لین دین کی قسم منتخب کریں', 'ur-PK'),
('936', 'lbl_SelectUnit', 'یونٹ منتخب کریں', 'ur-PK'),
('937', 'lbl_SelectVendor', 'فروشندہ منتخب کریں', 'ur-PK'),
('938', 'lbl_SelectVoucherType', 'واؤچر کی قسم منتخب کریں', 'ur-PK'),
('939', 'lbl_SelectYear', 'سال منتخب کریں', 'ur-PK'),
('940', 'lbl_Sendmoney', 'پیسے بھیجیں', 'ur-PK'),
('941', 'lbl_Service', 'سروس', 'ur-PK'),
('942', 'lbl_Setting', 'ترتیبات', 'ur-PK'),
('943', 'lbl_Settle', 'تصفیہ کریں', 'ur-PK'),
('944', 'lbl_SettleAmount', 'ادائیگی شدہ رقم', 'ur-PK'),
('945', 'lbl_SettleDays', 'ادائیگی شدہ دن', 'ur-PK'),
('946', 'lbl_Setup', 'ترتیب', 'ur-PK'),
('947', 'lbl_Share', 'شیئر کریں', 'ur-PK'),
('948', 'lbl_ShiftTimingChangeRequest', 'شفٹ کے وقت میں تبدیلی کی درخواست', 'ur-PK'),
('949', 'lbl_Shoes', 'جوتے', 'ur-PK'),
('950', 'lbl_Show', 'دکھائیں', 'ur-PK'),
('951', 'lbl_ShowAllEmployeeRequest', 'تمام ملازمین کی درخواستیں دکھائیں', 'ur-PK'),
('952', 'lbl_ShowAllNotification', 'تمام اطلاعات دکھائیں', 'ur-PK'),
('953', 'lbl_ShowAllProcessApproval', 'تمام عمل کی منظوری دکھائیں', 'ur-PK'),
('954', 'lbl_ShowReport', 'رپورٹ دکھائیں', 'ur-PK'),
('955', 'lbl_SideTablesRequest', 'سائیڈ ٹیبلز کی درخواست', 'ur-PK'),
('956', 'lbl_Signintoaccessyouremployeeportal.', 'ملازم پورٹل تک رسائی کے لیے سائن اِن کریں۔', 'ur-PK'),
('957', 'lbl_SignintoaccessyourUserportal.', 'صارف پورٹل تک رسائی کے لیے سائن اِن کریں۔', 'ur-PK'),
('958', 'lbl_Signintomanageyoursupplieraccount.', 'اپنا سپلائر اکاؤنٹ منظم کرنے کے لیے سائن اِن کریں۔', 'ur-PK'),
('959', 'lbl_Specification', 'تفصیل', 'ur-PK'),
('960', 'lbl_Sports', 'کھیل', 'ur-PK'),
('961', 'lbl_Starbucks', 'اسٹار بکس', 'ur-PK'),
('962', 'lbl_Start', 'آغاز', 'ur-PK'),
('963', 'lbl_StartDate', 'شروع ہونے کی تاریخ', 'ur-PK'),
('964', 'lbl_StartMonth', 'آغاز کا مہینہ', 'ur-PK'),
('965', 'lbl_StartYear', 'آغاز کا سال', 'ur-PK'),
('966', 'lbl_Status', 'حیثیت', 'ur-PK'),
('967', 'lbl_STN', 'سیلز ٹیکس نمبر', 'ur-PK'),
('968', 'lbl_STNRate', 'ایس ٹی این شرح', 'ur-PK'),
('969', 'lbl_Stock', 'اسٹاک', 'ur-PK'),
('970', 'lbl_StockCount', 'اسٹاک گنتی', 'ur-PK'),
('971', 'lbl_StockList', 'اسٹاک کی فہرست', 'ur-PK'),
('972', 'lbl_StockQuantity', 'اسٹاک کی مقدار', 'ur-PK'),
('973', 'lbl_StorageShelvesRequest', 'اسٹوریج شیلفز کی درخواست', 'ur-PK'),
('974', 'lbl_StoreManagement', 'اسٹور کا انتظام', 'ur-PK'),
('975', 'lbl_Street', 'گلی / سڑک', 'ur-PK'),
('976', 'lbl_SubQualification', 'ضمنی اہلیت', 'ur-PK'),
('977', 'lbl_SubQualificationID', 'ضمنی اہلیت  نمبر', 'ur-PK'),
('978', 'lbl_SubQualificationList', 'ضمنی اہلیت  کی فہرست', 'ur-PK'),
('979', 'lbl_SubQualificationName', 'ضمنی اہلیت  کا نام', 'ur-PK'),
('980', 'lbl_SupplierLogin', 'سپلائر لاگ اِن', 'ur-PK'),
('981', 'lbl_SupplierLogin-Pages', 'سپلائر لاگ اِن - صفحات', 'ur-PK'),
('982', 'lbl_Support', 'مدد', 'ur-PK'),
('983', 'lbl_SwitchesandHubsRequest', 'سوئچز اور ہبز کی درخواست', 'ur-PK'),
('984', 'lbl_TermsConditions', 'شرائط و ضوابط', 'ur-PK'),
('985', 'lbl_Third', 'تیسرا', 'ur-PK'),
('986', 'lbl_ThirdQuotationAmount', 'تیسری نرخ کی رقم', 'ur-PK'),
('987', 'lbl_ThirdQuotationID', 'تیسری نرخ کی شناخت', 'ur-PK'),
('988', 'lbl_ThirdQuotationPrice', 'تیسری نرخ کی قیمت', 'ur-PK'),
('989', 'lbl_ThirdVendor', 'تیسرا فروخت کنندہ', 'ur-PK'),
('990', 'lbl_ThumbEnrollment', 'انگوٹھا اندراج', 'ur-PK'),
('991', 'lbl_ThumbEnrollmentList', 'انگوٹھے کے اندراجات کی فہرست', 'ur-PK'),
('992', 'lbl_ThumbFormat', 'انگوٹھے کا فارمیٹ', 'ur-PK'),
('993', 'lbl_ThumbImpression', 'انگوٹھے کا نشان', 'ur-PK'),
('994', 'lbl_TimesheetCorrectionRequest', 'ٹائم شیٹ درستگی کی درخواست', 'ur-PK'),
('995', 'lbl_Tittle', 'عنوان', 'ur-PK'),
('996', 'lbl_ToChequeNo', 'چیک نمبر تک', 'ur-PK'),
('997', 'lbl_ToDate', 'آخری تاریخ', 'ur-PK'),
('998', 'lbl_ToDutySlot', 'ڈیوٹی سلاٹ تک', 'ur-PK'),
('999', 'lbl_Total', 'مکمل', 'ur-PK'),
('1000', 'lbl_TotalAccessCount', 'کل رسائی کی گنتی', 'ur-PK'),
('1001', 'lbl_TotalAmount', 'کل رقم', 'ur-PK'),
('1002', 'lbl_TotalBalance', 'کل بیلنس', 'ur-PK'),
('1003', 'lbl_TotalCreditAmount', 'کل کریڈٹ رقم', 'ur-PK'),
('1004', 'lbl_TotalDayOfAbsent', 'کل غیر حاضری کے دن', 'ur-PK'),
('1005', 'lbl_TotalDays', 'کل دن', 'ur-PK'),
('1006', 'lbl_TotalDebitAmount', 'کل ڈیبٹ رقم', 'ur-PK'),
('1007', 'lbl_TotalEndOfServiceDues', 'کل اختتامِ سروس واجبات', 'ur-PK'),
('1008', 'lbl_TotalExpenses', 'کل اخراجات', 'ur-PK'),
('1009', 'lbl_TotalHours', 'کل اوقات', 'ur-PK'),
('1010', 'lbl_TotalOrders', 'کل آرڈرز', 'ur-PK'),
('1011', 'lbl_TotalOverTimeDays', 'کل اوور ٹائم دن', 'ur-PK'),
('1012', 'lbl_TotalPages', 'چیک بُک کی فہرست', 'ur-PK'),
('1013', 'lbl_TotalRank', 'کل درجہ', 'ur-PK'),
('1014', 'lbl_TotalRevenues', 'کل آمدنیاں', 'ur-PK'),
('1015', 'lbl_TotalRole', 'کل کردار', 'ur-PK'),
('1016', 'lbl_TotalSalary', 'کل تنخواہ', 'ur-PK'),
('1017', 'lbl_TotalVacation', 'کل چھٹیاں', 'ur-PK'),
('1018', 'lbl_Transaction', 'لین دین', 'ur-PK'),
('1019', 'lbl_TransactionAccount', 'لین دین کا کھاتہ', 'ur-PK'),
('1020', 'lbl_TransactionType', 'لین دین کی قسم', 'ur-PK'),
('1021', 'lbl_Transfer', 'منتقلی', 'ur-PK'),
('1022', 'lbl_TransferVoucher', 'منتقلی واؤچر', 'ur-PK'),
('1023', 'lbl_TransferVoucher', 'ٹرانسفر واؤچر', 'ur-PK'),
('1024', 'lbl_TransferVoucherApproval', 'منتقلی ووچر کی منظوری', 'ur-PK'),
('1025', 'lbl_TransferVoucherID', 'ٹرانسفر واؤچر نمبر', 'ur-PK'),
('1026', 'lbl_TransferVoucherList', 'ٹرانسفر واؤچر کی فہرست', 'ur-PK'),
('1027', 'lbl_TravelExpensesRequest', 'سفر کے اخراجات کی درخواست', 'ur-PK'),
('1028', 'lbl_TrialBalance', 'آزمائشی بیلنس', 'ur-PK'),
('1029', 'lbl_TrialBalancePrint', 'آزمائشی بیلنس پرنٹ', 'ur-PK'),
('1030', 'lbl_TrialBalanceReport', 'آزمائشی بیلنس رپورٹ', 'ur-PK'),
('1031', 'lbl_T-shirt', 'ٹی شرٹ', 'ur-PK'),
('1032', 'lbl_TV', 'ٹی وی', 'ur-PK'),
('1033', 'lbl_Type', 'قسم', 'ur-PK'),
('1034', 'lbl_TypeCount', 'قسم کی تعداد', 'ur-PK'),
('1035', 'lbl_Unit', 'یونٹ', 'ur-PK'),
('1036', 'lbl_Unknown', 'نامعلوم', 'ur-PK'),
('1037', 'lbl_Update', 'اپ ڈیٹ کریں', 'ur-PK'),
('1038', 'lbl_Upload', ' اپ لوڈ', 'ur-PK'),
('1039', 'lbl_UploadDocument', 'دستاویز اپ لوڈ کریں', 'ur-PK'),
('1040', 'lbl_UploadFile', 'فائل اپ لوڈ کریں', 'ur-PK'),
('1041', 'lbl_UploadNewDocument', 'نئی دستاویز اپ لوڈ کریں', 'ur-PK'),
('1042', 'lbl_UPSRequest', 'یو پی ایس کی درخواست', 'ur-PK'),
('1043', 'lbl_USBFlashDrivesRequest', 'یو ایس بی فلیش ڈرائیوز کی درخواست', 'ur-PK'),
('1044', 'lbl_User', 'صارف', 'ur-PK'),
('1045', 'lbl_User', 'صارف', 'ur-PK'),
('1046', 'lbl_UserDetails', 'صارف کی تفصیل', 'ur-PK'),
('1047', 'lbl_UserID', 'صارف  نمبر', 'ur-PK'),
('1048', 'lbl_UserList', 'صارف  کی فہرست', 'ur-PK'),
('1049', 'lbl_UserLogin', 'صارف لاگ اِن', 'ur-PK'),
('1050', 'lbl_UserMonitor', 'صارف کی نگرانی', 'ur-PK'),
('1051', 'lbl_UserName', 'صارف  کا نام', 'ur-PK'),
('1052', 'lbl_UserRegistation', 'صارف کی رجسٹریشن', 'ur-PK'),
('1053', 'lbl_Vacation', 'چھٹی', 'ur-PK'),
('1054', 'lbl_VacationApproval', 'تعطیلات کی منظوری', 'ur-PK'),
('1055', 'lbl_VacationBalance', 'چھٹی کا بیلنس', 'ur-PK'),
('1056', 'lbl_VacationBalanceList', 'چھٹی کے بیلنس کی فہرست', 'ur-PK'),
('1057', 'lbl_VacationDate', 'چھٹی کی تاریخ', 'ur-PK'),
('1058', 'lbl_VacationDays', 'چھٹی کے دن', 'ur-PK'),
('1059', 'lbl_VacationDetails', 'چھٹیوں کی تفصیلات', 'ur-PK'),
('1060', 'lbl_VacationID', 'چھٹی نمبر', 'ur-PK'),
('1061', 'lbl_VacationList', 'چھٹیوں کی فہرست', 'ur-PK'),
('1062', 'lbl_VacationReport', 'چھٹی کی رپورٹ', 'ur-PK'),
('1063', 'lbl_VacationReportList', 'چھٹی کی رپورٹس کی فہرست', 'ur-PK'),
('1064', 'lbl_VacationSettle', 'چھٹی کی ادائیگی', 'ur-PK'),
('1065', 'lbl_VacationSettleApproval', 'تعطیلات تصفیہ منظوری', 'ur-PK'),
('1066', 'lbl_VacationSettleDetails', 'چھٹیوں کے تصفیے کی تفصیلات', 'ur-PK'),
('1067', 'lbl_VacationSettleID', 'چھٹی کی ادائیگی نمبر', 'ur-PK'),
('1068', 'lbl_VacationSettleList', 'چھٹی کی ادائیگی کی فہرست', 'ur-PK'),
('1069', 'lbl_VacationType', 'چھٹی کی قسم', 'ur-PK'),
('1070', 'lbl_VacationType', 'چھٹی کی قسم', 'ur-PK'),
('1071', 'lbl_VacationTypeID', 'چھٹی کی قسم  نمبر', 'ur-PK'),
('1072', 'lbl_VacationTypeList', 'چھٹی کی قسم  کی فہرست', 'ur-PK'),
('1073', 'lbl_VacationTypeName', 'چھٹی کی قسم  کا نام', 'ur-PK'),
('1074', 'lbl_VacationTypeName', 'چھٹی کی قسم کا نام', 'ur-PK'),
('1075', 'lbl_ValueofTax', 'ٹیکس کی مالیت', 'ur-PK'),
('1076', 'lbl_Vendor', 'سپلائر', 'ur-PK'),
('1077', 'lbl_VendorID', 'سپلائر نمبر', 'ur-PK'),
('1078', 'lbl_VendorList', 'سپلائر کی فہرست', 'ur-PK'),
('1079', 'lbl_VendorName', 'سپلائر کا نام', 'ur-PK'),
('1080', 'lbl_VendorOption', 'فروخت کنندہ کا انتخاب', 'ur-PK'),
('1081', 'lbl_VendorPayee', 'سپلائر وصول کنندہ', 'ur-PK'),
('1082', 'lbl_View', 'دیکھیں', 'ur-PK'),
('1083', 'lbl_ViewBadges', 'بیجز دیکھیں', 'ur-PK'),
('1084', 'lbl_ViewDetails', 'تفصیلات دیکھیں', 'ur-PK'),
('1085', 'lbl_ViewMore', 'مزید دیکھیں', 'ur-PK'),
('1086', 'lbl_VoucherID', 'واؤچر آئی ڈی', 'ur-PK'),
('1087', 'lbl_VoucherType', 'واؤچر کی قسم', 'ur-PK'),
('1088', 'lbl_VoucherTypeID', 'ووچر کی قسم نمبر', 'ur-PK'),
('1089', 'lbl_VoucherTypeList', 'ووچر کی اقسام کی فہرست', 'ur-PK'),
('1090', 'lbl_VoucherTypeName', 'ووچر کی قسم کا نام', 'ur-PK'),
('1091', 'lbl_VPNDevicesRequest', 'وی پی این ڈیوائسز کی درخواست', 'ur-PK'),
('1092', 'lbl_Wallet', 'والیٹ', 'ur-PK'),
('1093', 'lbl_WebcamRequest', 'ویب کیم کی درخواست', 'ur-PK'),
('1094', 'lbl_WelcometoEmployeeLogin!', 'ملازم لاگ اِن میں خوش آمدید!', 'ur-PK'),
('1095', 'lbl_WelcometoSupplierLogin', 'سپلائر لاگ اِن میں خوش آمدید', 'ur-PK'),
('1096', 'lbl_WelcometoUserLogin!', 'صارف لاگ اِن میں خوش آمدید!', 'ur-PK'),
('1097', 'lbl_WellcomeTo', 'خوش آمدید', 'ur-PK'),
('1098', 'lbl_WhatsApp', 'واٹس ایپ', 'ur-PK'),
('1099', 'lbl_Whiteboards/NoticeBoardsRequest', 'وائٹ بورڈز/نوٹس بورڈز کی درخواست', 'ur-PK'),
('1100', 'lbl_Wi-FiRouterRequest', 'وائی فائی روٹر کی درخواست', 'ur-PK'),
('1101', 'lbl_WorkDay', 'ورک ڈے', 'ur-PK'),
('1102', 'lbl_WorkDayDetails', 'ورک ڈے کی تفصیل', 'ur-PK'),
('1103', 'lbl_WorkDayID', 'ورک ڈے نمبر', 'ur-PK'),
('1104', 'lbl_WorkDayList', 'ورک ڈے کی فہرست', 'ur-PK'),
('1105', 'lbl_WorkExperience', 'کام کا تجربہ', 'ur-PK'),
('1106', 'lbl_WorkfromHomeRequest', 'گھر سے کام کی درخواست', 'ur-PK'),
('1107', 'lbl_WorkingDayManagement', 'کام کے دنوں کا نظم', 'ur-PK'),
('1108', 'lbl_WorkingSlot', 'ورکنگ سلاٹ', 'ur-PK'),
('1109', 'lbl_Year', 'سال', 'ur-PK'),
('1110', 'lbl_Yes', 'ہاں', 'ur-PK');

    ";
  }
}
